import 'dart:async';
import 'package:climate_storyteller/core/storage/secure_storage_service.dart';
import 'package:climate_storyteller/features/narrator/narration_result.dart';

class AppLanguage {
  final String name;
  final String nativeName;
  final String code;
  final String localeCode;
  final Map<VoiceStyle, String> cloudTtsVoices;

  const AppLanguage({
    required this.name,
    required this.nativeName,
    required this.code,
    required this.localeCode,
    required this.cloudTtsVoices,
  });
}

class LanguageService {
  LanguageService._();
  static final LanguageService instance = LanguageService._();

  AppLanguage _currentLanguage = supportedLanguages.first;
  final _streamCtrl = StreamController<AppLanguage>.broadcast();

  Stream<AppLanguage> get languageStream => _streamCtrl.stream;
  AppLanguage get currentLanguage => _currentLanguage;

  static const List<AppLanguage> supportedLanguages = [
    AppLanguage(
      name: 'English',
      nativeName: 'English',
      code: 'en',
      localeCode: 'en-US',
      cloudTtsVoices: {
        VoiceStyle.natural: 'en-US-Neural2-F',
        VoiceStyle.poetic: 'en-US-News-K',
        VoiceStyle.scientific: 'en-US-Neural2-H',
      },
    ),
    AppLanguage(
      name: 'Spanish',
      nativeName: 'Español',
      code: 'es',
      localeCode: 'es-ES',
      cloudTtsVoices: {
        VoiceStyle.natural: 'es-ES-Neural2-F',
        VoiceStyle.poetic: 'es-ES-Polyglot-1',
        VoiceStyle.scientific: 'es-ES-Neural2-F',
      },
    ),
    AppLanguage(
      name: 'French',
      nativeName: 'Français',
      code: 'fr',
      localeCode: 'fr-FR',
      cloudTtsVoices: {
        VoiceStyle.natural: 'fr-FR-Neural2-B',
        VoiceStyle.poetic: 'fr-FR-Polyglot-1',
        VoiceStyle.scientific: 'fr-FR-Neural2-C',
      },
    ),
    AppLanguage(
      name: 'German',
      nativeName: 'Deutsch',
      code: 'de',
      localeCode: 'de-DE',
      cloudTtsVoices: {
        VoiceStyle.natural: 'de-DE-Neural2-F',
        VoiceStyle.poetic: 'de-DE-Polyglot-1',
        VoiceStyle.scientific: 'de-DE-Neural2-H',
      },
    ),
    AppLanguage(
      name: 'Portuguese',
      nativeName: 'Português',
      code: 'pt',
      localeCode: 'pt-BR',
      cloudTtsVoices: {
        VoiceStyle.natural: 'pt-BR-Neural2-F',
        VoiceStyle.poetic: 'pt-BR-Polyglot-1',
        VoiceStyle.scientific: 'pt-BR-Neural2-H',
      },
    ),
    AppLanguage(
      name: 'Italian',
      nativeName: 'Italiano',
      code: 'it',
      localeCode: 'it-IT',
      cloudTtsVoices: {
        VoiceStyle.natural: 'it-IT-Neural2-C',
        VoiceStyle.poetic: 'it-IT-Polyglot-1',
        VoiceStyle.scientific: 'it-IT-Neural2-A',
      },
    ),
    AppLanguage(
      name: 'Hindi',
      nativeName: 'हिन्दी',
      code: 'hi',
      localeCode: 'hi-IN',
      cloudTtsVoices: {
        VoiceStyle.natural: 'hi-IN-Neural2-D',
        VoiceStyle.poetic: 'hi-IN-Neural2-F',
        VoiceStyle.scientific: 'hi-IN-Neural2-C',
      },
    ),
    AppLanguage(
      name: 'Japanese',
      nativeName: '日本語',
      code: 'ja',
      localeCode: 'ja-JP',
      cloudTtsVoices: {
        VoiceStyle.natural: 'ja-JP-Neural2-B',
        VoiceStyle.poetic: 'ja-JP-Neural2-C',
        VoiceStyle.scientific: 'ja-JP-Neural2-D',
      },
    ),
    AppLanguage(
      name: 'Chinese',
      nativeName: '中文',
      code: 'zh',
      localeCode: 'zh-CN',
      cloudTtsVoices: {
        VoiceStyle.natural: 'zh-CN-Neural2-F',
        VoiceStyle.poetic: 'zh-CN-Wavenet-B',
        VoiceStyle.scientific: 'zh-CN-Neural2-C',
      },
    ),
  ];

  Future<void> init() async {
    final code = await SecureStorageService.instance.getLanguageCode();
    if (code != null) {
      final match = supportedLanguages.firstWhere(
        (l) => l.code == code,
        orElse: () => supportedLanguages.first,
      );
      _currentLanguage = match;
    }
  }

  Future<void> setLanguage(String code) async {
    final match = supportedLanguages.firstWhere(
      (l) => l.code == code,
      orElse: () => supportedLanguages.first,
    );
    _currentLanguage = match;
    await SecureStorageService.instance.saveLanguageCode(code);
    _streamCtrl.add(match);
  }

  String translate(String key) {
    final langCode = _currentLanguage.code;
    return _translations[langCode]?[key] ?? _translations['en']?[key] ?? key;
  }

  static const Map<String, Map<String, String>> _translations = {
    'en': {
      'nav_explore': 'Explore',
      'nav_explore_sub': 'Interactive Map & Regions',
      'nav_story': 'Story',
      'nav_story_sub': 'Automated Story Chapters',
      'nav_settings': 'Settings',
      'nav_settings_sub': 'Liquid Galaxy & Setup',
      'drawer_title': 'Climate Storyteller',
      'drawer_subtitle': 'Liquid Galaxy Visualizer',
      'lg_connected': 'LG Rig Connected',
      'lg_disconnected': 'LG Rig Disconnected',
      'dark_theme': 'Dark Theme',
      'settings_title': 'Settings',
      'settings_sub': 'Configure Liquid Galaxy connection, themes & options',
      'sec_application': 'Application',
      'sec_api_keys': 'API Keys',
      'sec_about': 'About',
      'sec_lg_actions': 'LIQUID GALAXY ACTIONS',
      'sec_data_storage': 'DATA & STORAGE',
      'tile_language': 'Language',
      'tile_theme': 'Theme Mode',
      'theme_light': 'Light Mode',
      'theme_dark': 'Dark Mode',
      'theme_system': 'System Default',
      'tile_data_sources': 'Data Sources',
      'tile_data_sources_sub': 'NASA GIBS, NOAA, IPCC',
      'data_sources_title': 'Climate Data Sources',
      'data_sources_sub': 'How we retrieve & render Earth data',
      'ds_data_provided': 'Data Provided',
      'ds_how_we_get_it': 'How We Get It',
      'ds_nasa_gibs_desc': 'High-resolution satellite imagery tiles & environmental raster overlays.',
      'ds_nasa_gibs_how': 'Fetches real-time WMTS (EPSG:4326) tile layers directly from NASA Earthdata servers and formats them into dynamic KML GroundOverlays.',
      'ds_noaa_desc': 'Historical temperature anomalies, mean sea level trends, and NSIDC ice index.',
      'ds_noaa_how': 'Queries NOAA Climate Data Online API (v2) and Tides & Currents REST endpoints, generating Placemark time series on Liquid Galaxy.',
      'ds_ipcc_desc': 'CMIP6 climate projections and SSP scenarios (SSP1-2.6 to SSP5-8.5).',
      'ds_ipcc_how': 'Embeds IPCC 6th Assessment Report WGI/WGII dataset models with multi-era placemarks and regional boundary polygons.',
      'ds_openaq_desc': 'Global real-time PM2.5, PM10, NO2, and ground O3 air quality data.',
      'ds_openaq_how': 'Calls OpenAQ REST API v2 for live atmospheric readings across global megacities with intelligent offline estimations.',
      'ds_gfw_desc': 'Tropical deforestation alerts, canopy cover loss, and active fire tracking.',
      'ds_gfw_how': 'Parses NASA FIRMS VIIRS active fire CSV feeds and Hansen/UMD forest change data rendered directly onto Liquid Galaxy screens.',
      'tile_networklink': 'Set up NetworkLink',
      'tile_networklink_sub': 'Fix Google Earth sync',
      'tile_kml_cache': 'KML Cache',
      'tile_kml_cache_sub': 'Pre-load KML datasets',
      'tile_lg_diagnostics': 'LG Diagnostics',
      'tile_lg_diagnostics_sub': 'System & port check',
      'tile_api_setup': 'API Setup',
      'tile_api_setup_sub': 'Gemini AI & NOAA keys',
      'tile_about': 'About Storyteller',
      'tile_about_sub': 'GeSoC 2026 · Liquid Galaxy Project · v2.0.0',
      'btn_disconnect': 'Disconnect',
      'btn_connect_lg': 'Connect to LG Rig',
      'lg_status_connected': 'LG Rig · Connected',
      'lg_status_disconnected': 'LG Rig · Disconnected',
      'about_description': 'Climate Change Storyteller is a multi-screen visualization platform for Liquid Galaxy. It displays interactive KML layers and timelines to tell the story of Earth\'s changing climate.',
      'about_org': 'Organization',
      'about_prog': 'Program',
      'about_sys': 'Target System',
      'about_tech': 'Core Tech',
      'btn_close': 'Close',
      'btn_cancel': 'Cancel',
      'btn_delete': 'Delete',
      'explore_title': 'Explore Climate Regions',
      'explore_sub': 'Tap a pin on map to auto-open description balloon on Right-Most LG screen',
      'cat_all': 'All',
      'cat_glaciers': 'Glaciers',
      'cat_sealevel': 'Sea Level',
      'cat_forests': 'Forests',
      'cat_heat': 'Heat',
      'climate_regions': 'CLIMATE REGIONS',
      'remove_all_added': 'Remove All Added',
      'remove_all_title': 'Remove All Added Locations?',
      'remove_all_confirm_desc': 'Are you sure you want to remove all user-added locations? This action cannot be undone.',
      'btn_remove_all': 'Remove All',
      'add_custom_region': 'Add Custom Region',
      'all_locations_removed': 'All user-added locations removed.',
      'badge_custom': 'Custom',
      'tap_fullscreen': 'Tap image to view full-screen',
      'narration_generating': 'Generating unique AI narration…',
      'narration_playing': 'AI Narration Playing',
      'narration_paused': 'Narration Paused',
      'narration_title': 'AI Storyteller Narration',
      'btn_stop_narration': 'Stop Narration',
      'btn_resume_narration': 'Resume Narration',
      'btn_start_narration': 'Start Narration',
      'time_slider_title': 'LG KML Time Slider (1850 – 2150)',
      'select_region_hint': 'Select a climate region to activate LG time slider',
      'btn_reload_kml': 'Reload KML',
      'btn_select_pin': 'Select a Region Pin',
      'btn_orbit': '3D Orbit',
      'btn_stop_orbit': 'Stop Orbit',
      'uploading_kml': 'Uploading KML to LG Rig...',
      'slider_speed': 'Speed',
      'era_pre_industrial': 'Pre-Industrial',
      'era_mid_century': 'Mid-Century',
      'era_late_century': 'Late Century',
      'era_present': 'Present',
      'era_mid_projection': 'Mid Projection',
      'era_projected_2100': 'Projected 2100',
      'story_mode_title': 'Story Mode',
      'story_mode_sub': 'Automated presentation for Liquid Galaxy',
      'story_progress': 'STORY PROGRESS',
      'chapters_title': 'Chapters',
      'story_press_play': 'Press Play to begin the story',
      'story_playing': 'Playing',
      'story_paused': 'Paused',
      'story_preparing': 'Preparing story chapter...',
      'ch_0_title': 'The World Before',
      'ch_0_sub': '1900 · Pre-industrial Earth',
      'ch_1_title': 'The Great Melt',
      'ch_1_sub': '2026 · Arctic Circle today',
      'ch_2_title': 'Forests Falling',
      'ch_2_sub': '2026 · Amazon Basin',
      'ch_3_title': 'Rising Waters',
      'ch_3_sub': '2100 · Maldives',
      'ch_4_title': 'A Choice Remains',
      'ch_4_sub': '2100 · Pacific Islands',
      'btn_clear_kml': 'Clear KML',
      'kml_cleared_msg': 'All KMLs removed from Liquid Galaxy in one go!',
      'live_climate_alerts': 'LIVE CLIMATE ALERTS',
      'btn_refresh': 'Refresh',
      'loading_alerts': 'Loading climate alerts...',
      'climate_layers': 'Climate Layers (KML)',
      'btn_fly_to_region': 'Fly to Region',
      'btn_orbit_region': 'Orbit Region (360°)',
      'not_connected_lg': 'Not connected to LG Rig',
      'status_viewing': 'Viewing on LG',
      'status_send_to_lg': 'Send to LG',
      'onboarding_next': 'Next',
      'onboarding_get_started': 'Get Started',
      'onboarding_skip': 'Skip',
      'story_done': 'Done',
      'story_chapter': 'Chapter',
      'story_progress_chapter': 'Chapter progress',
      'story_chapters_count': '5 Chapters · Auto-play',
      'theme_light_sub': 'Clean light mode',
      'theme_dark_sub': 'Default dark mode',
      'theme_system_sub': 'Match system settings',
      'btn_back': 'Back',
      'story_syncing': 'Syncing',
      'story_speaking': 'Speaking narration…',
      'story_chapter_complete': '✓ Chapter complete',
      'story_all_complete': '🎬 Story complete — all 5 chapters played',
      'story_paused_msg': 'Paused — tap Play to resume',
    },
    'es': {
      'nav_explore': 'Explorar',
      'nav_explore_sub': 'Mapa Interactivo y Regiones',
      'nav_story': 'Historia',
      'nav_story_sub': 'Capítulos de Historia Automatizados',
      'nav_settings': 'Ajustes',
      'nav_settings_sub': 'Liquid Galaxy y Configuración',
      'drawer_title': 'Narrador Climático',
      'drawer_subtitle': 'Visualizador Liquid Galaxy',
      'lg_connected': 'LG Rig Conectado',
      'lg_disconnected': 'LG Rig Desconectado',
      'dark_theme': 'Tema Oscuro',
      'settings_title': 'Ajustes',
      'settings_sub': 'Configurar conexión de Liquid Galaxy, temas y opciones',
      'sec_application': 'Aplicación',
      'sec_api_keys': 'Claves de API',
      'sec_about': 'Acerca de',
      'sec_lg_actions': 'ACCIONES DE LIQUID GALAXY',
      'sec_data_storage': 'DATOS Y ALMACENAMIENTO',
      'tile_language': 'Idioma',
      'tile_theme': 'Modo de Tema',
      'theme_light': 'Modo Claro',
      'theme_dark': 'Modo Oscuro',
      'theme_system': 'Predeterminado del Sistema',
      'tile_data_sources': 'Fuentes de Datos',
      'tile_data_sources_sub': 'NASA GIBS, NOAA, IPCC',
      'data_sources_title': 'Fuentes de Datos Climáticos',
      'data_sources_sub': 'Cómo recuperamos y renderizamos datos de la Tierra',
      'ds_data_provided': 'Datos Proporcionados',
      'ds_how_we_get_it': 'Cómo los Obtenemos',
      'ds_nasa_gibs_desc': 'Teselas de imágenes satelitales de alta resolución y superposiciones ráster ambientales.',
      'ds_nasa_gibs_how': 'Obtiene capas de teselas WMTS (EPSG:4326) en tiempo real directamente de los servidores de NASA Earthdata y las formatea en GroundOverlays de KML dinámicos.',
      'ds_noaa_desc': 'Anomalías históricas de temperatura, tendencias del nivel medio del mar e índice de hielo de NSIDC.',
      'ds_noaa_how': 'Consulta la API de datos climáticos en línea de NOAA (v2) y puntos finales REST de Mareas y Corrientes, generando series temporales de Placemarks en Liquid Galaxy.',
      'ds_ipcc_desc': 'Proyecciones climáticas CMIP6 y escenarios SSP (SSP1-2.6 a SSP5-8.5).',
      'ds_ipcc_how': 'Integra modelos de datos del 6º Informe de Evaluación del IPCC WGI/WGII con marcas de posición de múltiples épocas y polígonos de límites regionales.',
      'ds_openaq_desc': 'Datos globales de calidad del aire en tiempo real para PM2.5, PM10, NO2 y O3 a nivel del suelo.',
      'ds_openaq_how': 'Llama a la API REST v2 de OpenAQ para lecturas atmosféricas en vivo en megaciudades mundiales con estimaciones inteligentes sin conexión.',
      'ds_gfw_desc': 'Alertas de deforestación tropical, pérdida de dosel arbóreo y seguimiento de incendios activos.',
      'ds_gfw_how': 'Analiza fuentes CSV de incendios activos VIIRS de NASA FIRMS y datos de cambios forestales de Hansen/UMD directamente en las pantallas de Liquid Galaxy.',
      'tile_networklink': 'Configurar NetworkLink',
      'tile_networklink_sub': 'Corregir sincronización de Google Earth',
      'tile_kml_cache': 'Caché de KML',
      'tile_kml_cache_sub': 'Precargar conjuntos de datos KML',
      'tile_lg_diagnostics': 'Diagnósticos de LG',
      'tile_lg_diagnostics_sub': 'Verificación de sistema y puertos',
      'tile_api_setup': 'Configuración de API',
      'tile_api_setup_sub': 'Claves de IA Gemini y NOAA',
      'tile_about': 'Acerca del Narrador',
      'tile_about_sub': 'GeSoC 2026 · Liquid Galaxy Project · v2.0.0',
      'btn_disconnect': 'Desconectar',
      'btn_connect_lg': 'Conectarse a LG Rig',
      'lg_status_connected': 'LG Rig · Conectado',
      'lg_status_disconnected': 'LG Rig · Desconectado',
      'about_description': 'Climate Change Storyteller es una plataforma de visualización multipantalla para Liquid Galaxy. Muestra capas KML interactivas y líneas temporales para contar la historia del cambio climático en la Tierra.',
      'about_org': 'Organización',
      'about_prog': 'Programa',
      'about_sys': 'Sistema Objetivo',
      'about_tech': 'Tecnología Principal',
      'btn_close': 'Cerrar',
      'btn_cancel': 'Cancelar',
      'btn_delete': 'Eliminar',
      'explore_title': 'Explorar Regiones Climáticas',
      'explore_sub': 'Toque un marcador para abrir el globo informativo en la pantalla derecha de LG',
      'cat_all': 'Todos',
      'cat_glaciers': 'Glaciares',
      'cat_sealevel': 'Nivel del Mar',
      'cat_forests': 'Bosques',
      'cat_heat': 'Calor',
      'climate_regions': 'REGIONES CLIMÁTICAS',
      'remove_all_added': 'Eliminar Todos los Agregados',
      'remove_all_title': '¿Eliminar todas las ubicaciones agregadas?',
      'remove_all_confirm_desc': '¿Está seguro de que desea eliminar todas las ubicaciones agregadas por el usuario? Esta acción no se puede deshacer.',
      'btn_remove_all': 'Eliminar Todos',
      'add_custom_region': 'Agregar Región Personalizada',
      'all_locations_removed': 'Todas las ubicaciones agregadas fueron eliminadas.',
      'badge_custom': 'Personalizado',
      'tap_fullscreen': 'Toque la imagen para ver en pantalla completa',
      'narration_generating': 'Generando narración única con IA…',
      'narration_playing': 'Reproduciendo Narración de IA',
      'narration_paused': 'Narración Pausada',
      'narration_title': 'Narración del Storyteller de IA',
      'btn_stop_narration': 'Detener Narración',
      'btn_resume_narration': 'Reanudar Narración',
      'btn_start_narration': 'Iniciar Narración',
      'time_slider_title': 'Control Temporal KML en LG (1850 – 2150)',
      'select_region_hint': 'Seleccione una región climática para activar el control temporal',
      'btn_reload_kml': 'Recargar KML',
      'btn_select_pin': 'Seleccione un Marcador',
      'btn_orbit': 'Órbita 3D',
      'btn_stop_orbit': 'Detener Órbita',
      'uploading_kml': 'Subiendo KML a LG Rig...',
      'slider_speed': 'Velocidad',
      'era_pre_industrial': 'Preindustrial',
      'era_mid_century': 'Mediados de Siglo',
      'era_late_century': 'Finales de Siglo',
      'era_present': 'Actual',
      'era_mid_projection': 'Proyección Media',
      'era_projected_2100': 'Proyectado 2100',
      'story_mode_title': 'Modo Historia',
      'story_mode_sub': 'Presentación automatizada para Liquid Galaxy',
      'story_progress': 'PROGRESO DE LA HISTORIA',
      'chapters_title': 'Capítulos',
      'story_press_play': 'Presiona Reproducir para comenzar la historia',
      'story_playing': 'Reproduciendo',
      'story_paused': 'En pausa',
      'story_preparing': 'Preparando capítulo de la historia...',
      'ch_0_title': 'El Mundo de Antes',
      'ch_0_sub': '1900 · Tierra preindustrial',
      'ch_1_title': 'El Gran Deshielo',
      'ch_1_sub': '2026 · Círculo Polar Ártico hoy',
      'ch_2_title': 'Bosques que Caen',
      'ch_2_sub': '2026 · Cuenca del Amazonas',
      'ch_3_title': 'Aguas Crecientes',
      'ch_3_sub': '2100 · Maldivas',
      'ch_4_title': 'Una Elección Permanece',
      'ch_4_sub': '2100 · Islas del Pacífico',
      'btn_clear_kml': 'Borrar KML',
      'kml_cleared_msg': '¡Todos los KML eliminados de Liquid Galaxy de una vez!',
      'live_climate_alerts': 'ALERTAS CLIMÁTICAS EN VIVO',
      'btn_refresh': 'Actualizar',
      'loading_alerts': 'Cargando alertas climáticas...',
      'climate_layers': 'Capas Climáticas (KML)',
      'btn_fly_to_region': 'Volar a la Región',
      'btn_orbit_region': 'Orbitar Región (360°)',
      'not_connected_lg': 'No conectado a LG Rig',
      'status_viewing': 'Visualizando en LG',
      'status_send_to_lg': 'Enviar a LG',
      'onboarding_next': 'Siguiente',
      'onboarding_get_started': 'Comenzar',
      'onboarding_skip': 'Omitir',
      'story_done': 'Hecho',
      'story_chapter': 'Capítulo',
      'story_progress_chapter': 'Progreso del capítulo',
      'story_chapters_count': '5 Capítulos · Reproducción automática',
      'theme_light_sub': 'Modo claro limpio',
      'theme_dark_sub': 'Modo oscuro predeterminado',
      'theme_system_sub': 'Coincidir con el sistema',
      'btn_back': 'Atrás',
      'story_syncing': 'Sincronizando',
      'story_speaking': 'Narrando…',
      'story_chapter_complete': '✓ Capítulo completado',
      'story_all_complete': '🎬 Historia completada — los 5 capítulos reproducidos',
      'story_paused_msg': 'Pausado — toca Reproducir para reanudar',
    },
    'fr': {
      'nav_explore': 'Explorer',
      'nav_explore_sub': 'Carte Interactive et Régions',
      'nav_story': 'Histoire',
      'nav_story_sub': 'Chapitres d\'Histoire Automatisés',
      'nav_settings': 'Paramètres',
      'nav_settings_sub': 'Liquid Galaxy et Configuration',
      'drawer_title': 'Raconteur Climat',
      'drawer_subtitle': 'Visualiseur Liquid Galaxy',
      'lg_connected': 'LG Rig Connecté',
      'lg_disconnected': 'LG Rig Déconnecté',
      'dark_theme': 'Thème Sombre',
      'settings_title': 'Paramètres',
      'settings_sub': 'Configurer la connexion Liquid Galaxy, thèmes et options',
      'sec_application': 'Application',
      'sec_api_keys': 'Clés API',
      'sec_about': 'À propos',
      'sec_lg_actions': 'ACTIONS LIQUID GALAXY',
      'sec_data_storage': 'DONNÉES ET STOCKAGE',
      'tile_language': 'Langue',
      'tile_theme': 'Mode de Thème',
      'theme_light': 'Mode Clair',
      'theme_dark': 'Mode Sombre',
      'theme_system': 'Par Défaut du Système',
      'tile_data_sources': 'Sources de Données',
      'tile_data_sources_sub': 'NASA GIBS, NOAA, IPCC',
      'data_sources_title': 'Sources de Données Climatiques',
      'data_sources_sub': 'Comment nous récupérons et affichons les données terrestres',
      'ds_data_provided': 'Données Fournies',
      'ds_how_we_get_it': 'Comment Nous les Obtenons',
      'ds_nasa_gibs_desc': 'Tuiles d\'images satellites haute résolution et superpositions raster environnementales.',
      'ds_nasa_gibs_how': 'Récupère les couches de tuiles WMTS (EPSG:4326) directement depuis les serveurs NASA Earthdata en GroundOverlays KML dynamiques.',
      'ds_noaa_desc': 'Anomalies historiques de température, tendances du niveau de la mer et indice des glaces NSIDC.',
      'ds_noaa_how': 'Interroge les API de données climatiques NOAA en ligne (v2) et les points REST Marées et Courants pour générer des séries temporelles sur Liquid Galaxy.',
      'ds_ipcc_desc': 'Projections climatiques CMIP6 et scénarios SSP (SSP1-2.6 à SSP5-8.5).',
      'ds_ipcc_how': 'Intègre les modèles du 6e rapport du GIEC (WGI/WGII) avec des repères multi-époques et des polygones régionaux.',
      'ds_openaq_desc': 'Données mondiales en temps réel sur la qualité de l\'air : PM2.5, PM10, NO2 et O3.',
      'ds_openaq_how': 'Interroge l\'API REST OpenAQ v2 pour les relevés atmosphériques en direct des mégapoles mondiales avec estimations hors ligne intelligentes.',
      'ds_gfw_desc': 'Alertes de déforestation tropicale, perte de couvert végétal et suivi des incendies actifs.',
      'ds_gfw_how': 'Analyse les flux CSV NASA FIRMS VIIRS et les données Hansen/UMD affichés directement sur les écrans de Liquid Galaxy.',
      'tile_networklink': 'Configurer NetworkLink',
      'tile_networklink_sub': 'Corriger la synchronisation Google Earth',
      'tile_kml_cache': 'Cache KML',
      'tile_kml_cache_sub': 'Précharger les jeux de données KML',
      'tile_lg_diagnostics': 'Diagnostics LG',
      'tile_lg_diagnostics_sub': 'Contrôle du système et des ports',
      'tile_api_setup': 'Configuration API',
      'tile_api_setup_sub': 'Clés IA Gemini et NOAA',
      'tile_about': 'À propos du Raconteur',
      'tile_about_sub': 'GeSoC 2026 · Projet Liquid Galaxy · v2.0.0',
      'btn_disconnect': 'Déconnecter',
      'btn_connect_lg': 'Connecter au LG Rig',
      'lg_status_connected': 'LG Rig · Connecté',
      'lg_status_disconnected': 'LG Rig · Déconnecté',
      'about_description': 'Climate Change Storyteller est une plateforme de visualisation multi-écrans pour Liquid Galaxy. Elle affiche des couches KML interactives et des chronologies pour raconter l\'histoire du climat changeant de la Terre.',
      'about_org': 'Organisation',
      'about_prog': 'Programme',
      'about_sys': 'Système Cible',
      'about_tech': 'Technologie Principale',
      'btn_close': 'Fermer',
      'btn_cancel': 'Annuler',
      'btn_delete': 'Supprimer',
      'explore_title': 'Explorer les Régions Climatiques',
      'explore_sub': 'Touchez une épingle pour afficher le ballon d\'information sur l\'écran droit de LG',
      'cat_all': 'Tous',
      'cat_glaciers': 'Glaciers',
      'cat_sealevel': 'Niveau de la Mer',
      'cat_forests': 'Forêts',
      'cat_heat': 'Chaleur',
      'climate_regions': 'RÉGIONS CLIMATIQUES',
      'remove_all_added': 'Supprimer Tous les Ajoutés',
      'remove_all_title': 'Supprimer tous les emplacements ajoutés ?',
      'remove_all_confirm_desc': 'Êtes-vous sûr de vouloir supprimer tous les emplacements ajoutés ? Cette action est irréversible.',
      'btn_remove_all': 'Supprimer Tout',
      'add_custom_region': 'Ajouter une Région Personnalisée',
      'all_locations_removed': 'Tous les emplacements ajoutés ont été supprimés.',
      'badge_custom': 'Personnalisé',
      'tap_fullscreen': 'Touchez l\'image pour l\'afficher en plein écran',
      'narration_generating': 'Génération d\'une narration IA unique…',
      'narration_playing': 'Lecture de la Narration IA',
      'narration_paused': 'Narration en Pause',
      'narration_title': 'Narration du Raconteur IA',
      'btn_stop_narration': 'Arrêter la Narration',
      'btn_resume_narration': 'Reprendre la Narration',
      'btn_start_narration': 'Démarrer la Narration',
      'time_slider_title': 'Curseur Temporel KML LG (1850 – 2150)',
      'select_region_hint': 'Sélectionnez une région pour activer le curseur temporel',
      'btn_reload_kml': 'Recharger KML',
      'btn_select_pin': 'Sélectionnez une Épingle',
      'btn_orbit': 'Orbite 3D',
      'btn_stop_orbit': 'Arrêter l\'Orbite',
      'uploading_kml': 'Envoi du KML vers LG Rig...',
      'slider_speed': 'Vitesse',
      'era_pre_industrial': 'Pré-industriel',
      'era_mid_century': 'Milieu de Siècle',
      'era_late_century': 'Fin de Siècle',
      'era_present': 'Présent',
      'era_mid_projection': 'Projection Moyenne',
      'era_projected_2100': 'Projeté 2100',
      'story_mode_title': 'Mode Histoire',
      'story_mode_sub': 'Présentation automatisée pour Liquid Galaxy',
      'story_progress': 'PROGRESSION DE L\'HISTOIRE',
      'chapters_title': 'Chapitres',
      'story_press_play': 'Appuyez sur Lecture pour commencer l\'histoire',
      'story_playing': 'En cours',
      'story_paused': 'En pause',
      'story_preparing': 'Préparation du chapitre...',
      'ch_0_title': 'Le Monde d\'Avant',
      'ch_0_sub': '1900 · Terre préindustrielle',
      'ch_1_title': 'La Grande Fonte',
      'ch_1_sub': '2026 · Cercle Arctique aujourd\'hui',
      'ch_2_title': 'Les Forêts Tombent',
      'ch_2_sub': '2026 · Bassin Amazonien',
      'ch_3_title': 'La Montée des Eaux',
      'ch_3_sub': '2100 · Maldives',
      'ch_4_title': 'Un Choix Demeure',
      'ch_4_sub': '2100 · Îles du Pacifique',
      'btn_clear_kml': 'Effacer KML',
      'kml_cleared_msg': 'Tous les KML ont été supprimés de Liquid Galaxy d\'un coup !',
      'live_climate_alerts': 'ALERTES CLIMATIQUES EN DIRECT',
      'btn_refresh': 'Actualiser',
      'loading_alerts': 'Chargement des alertes...',
      'climate_layers': 'Couches Climatiques (KML)',
      'btn_fly_to_region': 'Voler vers la Région',
      'btn_orbit_region': 'Orbiter la Région (360°)',
      'not_connected_lg': 'Non connecté au LG Rig',
      'status_viewing': 'En cours sur LG',
      'status_send_to_lg': 'Envoyer à LG',
      'onboarding_next': 'Suivant',
      'onboarding_get_started': 'Commencer',
      'onboarding_skip': 'Passer',
      'story_done': 'Terminé',
      'story_chapter': 'Chapitre',
      'story_progress_chapter': 'Progression du chapitre',
      'story_chapters_count': '5 Chapitres · Lecture automatique',
      'theme_light_sub': 'Mode clair épuré',
      'theme_dark_sub': 'Mode sombre par défaut',
      'theme_system_sub': 'Selon les paramètres système',
      'btn_back': 'Retour',
      'story_syncing': 'Synchronisation',
      'story_speaking': 'Narration en cours…',
      'story_chapter_complete': '✓ Chapitre terminé',
      'story_all_complete': '🎬 Histoire terminée — les 5 chapitres lus',
      'story_paused_msg': 'En pause — appuyez sur Lecture pour reprendre',
    },
    'de': {
      'nav_explore': 'Entdecken',
      'nav_explore_sub': 'Interaktive Karte & Regionen',
      'nav_story': 'Geschichte',
      'nav_story_sub': 'Automatisierte Geschichtenkapitel',
      'nav_settings': 'Einstellungen',
      'nav_settings_sub': 'Liquid Galaxy & Einrichtung',
      'drawer_title': 'Klima-Erzähler',
      'drawer_subtitle': 'Liquid Galaxy Visualisierer',
      'lg_connected': 'LG Rig Verbunden',
      'lg_disconnected': 'LG Rig Getrennt',
      'dark_theme': 'Dunkles Design',
      'settings_title': 'Einstellungen',
      'settings_sub': 'Konfigurieren Sie LG-Verbindung, Designs & Optionen',
      'sec_application': 'Anwendung',
      'sec_api_keys': 'API-Schlüssel',
      'sec_about': 'Über',
      'sec_lg_actions': 'LIQUID GALAXY AKTIONEN',
      'sec_data_storage': 'DATEN & SPEICHER',
      'tile_language': 'Sprache',
      'tile_theme': 'Design-Modus',
      'theme_light': 'Heller Modus',
      'theme_dark': 'Dunkler Modus',
      'theme_system': 'Systemstandard',
      'tile_data_sources': 'Datenquellen',
      'tile_data_sources_sub': 'NASA GIBS, NOAA, IPCC',
      'data_sources_title': 'Klimadatenquellen',
      'data_sources_sub': 'Wie wir Erddaten abrufen & darstellen',
      'ds_data_provided': 'Bereitgestellte Daten',
      'ds_how_we_get_it': 'Wie wir sie erhalten',
      'ds_nasa_gibs_desc': 'Hochauflösende Satellitenbildkacheln und Umwelt-Raster-Overlays.',
      'ds_nasa_gibs_how': 'Ruft Echtzeit-WMTS-Kachelebenen (EPSG:4326) direkt von NASA Earthdata ab und formatiert sie in dynamische KML GroundOverlays.',
      'ds_noaa_desc': 'Historische Temperaturanomalien, Trends des mittleren Meeresspiegels und NSIDC-Eisindex.',
      'ds_noaa_how': 'Fragt NOAA Climate Data Online API (v2) und Gezeiten-REST-Endpunkte ab, um Zeitreihen-Ortsmarken auf Liquid Galaxy zu erstellen.',
      'ds_ipcc_desc': 'CMIP6-Klimaprojektionen und SSP-Szenarien (SSP1-2.6 bis SSP5-8.5).',
      'ds_ipcc_how': 'Bettet Modelle des 6. Sachstandsberichts des IPCC (WGI/WGII) mit Mehrepochen-Ortsmarken und regionalen Grenzpolygonen ein.',
      'ds_openaq_desc': 'Globale Echtzeit-Luftqualitätsdaten für PM2.5, PM10, NO2 und bodennahes Ozon.',
      'ds_openaq_how': 'Ruft OpenAQ REST API v2 für Live-Atmosphärendaten aus globalen Megastädten mit intelligenten Offline-Schätzungen ab.',
      'ds_gfw_desc': 'Tropische Entwaldungswarnungen, Kronendachverlust und Verfolgung aktiver Brände.',
      'ds_gfw_how': 'Parst NASA FIRMS VIIRS Branddaten und Hansen/UMD-Waldveränderungsdaten direkt auf Liquid Galaxy-Bildschirmen.',
      'tile_networklink': 'NetworkLink Einrichten',
      'tile_networklink_sub': 'Google Earth Synchronisation reparieren',
      'tile_kml_cache': 'KML-Cache',
      'tile_kml_cache_sub': 'KML-Datensätze vorab laden',
      'tile_lg_diagnostics': 'LG-Diagnose',
      'tile_lg_diagnostics_sub': 'System- und Portprüfung',
      'tile_api_setup': 'API-Einrichtung',
      'tile_api_setup_sub': 'Gemini KI & NOAA Schlüssel',
      'tile_about': 'Über Storyteller',
      'tile_about_sub': 'GeSoC 2026 · Liquid Galaxy Projekt · v2.0.0',
      'btn_disconnect': 'Trennen',
      'btn_connect_lg': 'Mit LG Rig Verbinden',
      'lg_status_connected': 'LG Rig · Verbunden',
      'lg_status_disconnected': 'LG Rig · Getrennt',
      'about_description': 'Climate Change Storyteller ist eine Multi-Screen-Visualisierungsplattform für Liquid Galaxy. Sie zeigt interaktive KML-Ebenen und Zeitleisten, um die Geschichte des sich verändernden Erdklimas zu erzählen.',
      'about_org': 'Organisation',
      'about_prog': 'Programm',
      'about_sys': 'Zielsystem',
      'about_tech': 'Kerntechnologie',
      'btn_close': 'Schließen',
      'btn_cancel': 'Abbrechen',
      'btn_delete': 'Löschen',
      'explore_title': 'Klimaregionen Erkunden',
      'explore_sub': 'Tippen Sie auf eine Markierung für Infoballons auf dem rechten LG-Bildschirm',
      'cat_all': 'Alle',
      'cat_glaciers': 'Gletscher',
      'cat_sealevel': 'Meeresspiegel',
      'cat_forests': 'Wälder',
      'cat_heat': 'Hitze',
      'climate_regions': 'KLIMAREGIONEN',
      'remove_all_added': 'Alle Hinzugefügten Entfernen',
      'remove_all_title': 'Alle hinzugefügten Orte entfernen?',
      'remove_all_confirm_desc': 'Sind Sie sicher, dass Sie alle hinzugefügten Orte entfernen möchten? Dies kann nicht rückgängig gemacht werden.',
      'btn_remove_all': 'Alle Entfernen',
      'add_custom_region': 'Eigene Region Hinzufügen',
      'all_locations_removed': 'Alle hinzugefügten Orte wurden entfernt.',
      'badge_custom': 'Benutzerdefiniert',
      'tap_fullscreen': 'Bild für Vollbild antippen',
      'narration_generating': 'Generiere einzigartige KI-Erzählung…',
      'narration_playing': 'KI-Erzählung Läuft',
      'narration_paused': 'Erzählung Pausiert',
      'narration_title': 'KI-Storyteller Erzählung',
      'btn_stop_narration': 'Erzählung Stoppen',
      'btn_resume_narration': 'Erzählung Fortsetzen',
      'btn_start_narration': 'Erzählung Starten',
      'time_slider_title': 'LG KML Zeitschieberegler (1850 – 2150)',
      'select_region_hint': 'Wählen Sie eine Region, um den Zeitschieberegler zu aktivieren',
      'btn_reload_kml': 'KML Neu Laden',
      'btn_select_pin': 'Wählen Sie eine Markierung',
      'btn_orbit': '3D-Orbit',
      'btn_stop_orbit': 'Orbit Stoppen',
      'uploading_kml': 'Lade KML auf LG Rig hoch...',
      'slider_speed': 'Geschwindigkeit',
      'era_pre_industrial': 'Vorindustriell',
      'era_mid_century': 'Mitte des Jahrhunderts',
      'era_late_century': 'Spätes Jahrhundert',
      'era_present': 'Gegenwart',
      'era_mid_projection': 'Mittlere Projektion',
      'era_projected_2100': 'Prognose 2100',
      'story_mode_title': 'Story-Modus',
      'story_mode_sub': 'Automatisierte Präsentation für Liquid Galaxy',
      'story_progress': 'STORY-FORTSCHRITT',
      'chapters_title': 'Kapitel',
      'story_press_play': 'Drücken Sie Wiedergabe, um die Story zu starten',
      'story_playing': 'Wird abgespielt',
      'story_paused': 'Pausiert',
      'story_preparing': 'Bereite Story-Kapitel vor...',
      'ch_0_title': 'Die Welt Zuvor',
      'ch_0_sub': '1900 · Vorindustrielle Erde',
      'ch_1_title': 'Das Große Schmelzen',
      'ch_1_sub': '2026 · Polarkreis heute',
      'ch_2_title': 'Fallende Wälder',
      'ch_2_sub': '2026 · Amazonasbecken',
      'ch_3_title': 'Steigende Wasser',
      'ch_3_sub': '2100 · Malediven',
      'ch_4_title': 'Eine Wahl Bleibt',
      'ch_4_sub': '2100 · Pazifikinseln',
      'btn_clear_kml': 'KML Löschen',
      'kml_cleared_msg': 'Alle KMLs wurden auf einmal von Liquid Galaxy entfernt!',
      'live_climate_alerts': 'LIVE-KLIMAWARNUNGEN',
      'btn_refresh': 'Aktualisieren',
      'loading_alerts': 'Lade Klimawarnungen...',
      'climate_layers': 'Klimaschichten (KML)',
      'btn_fly_to_region': 'Zur Region Fliegen',
      'btn_orbit_region': 'Region Umkreisen (360°)',
      'not_connected_lg': 'Nicht mit LG Rig verbunden',
      'status_viewing': 'Wird auf LG angezeigt',
      'status_send_to_lg': 'An LG Senden',
      'onboarding_next': 'Weiter',
      'onboarding_get_started': 'Loslegen',
      'onboarding_skip': 'Überspringen',
      'story_done': 'Fertig',
      'story_chapter': 'Kapitel',
      'story_progress_chapter': 'Kapitelfortschritt',
      'story_chapters_count': '5 Kapitel · Automatische Wiedergabe',
      'theme_light_sub': 'Klarer Heller Modus',
      'theme_dark_sub': 'Standard-Dunkelmodus',
      'theme_system_sub': 'Systemeinstellungen anpassen',
      'btn_back': 'Zurück',
      'story_syncing': 'Synchronisieren',
      'story_speaking': 'Erzählung spricht…',
      'story_chapter_complete': '✓ Kapitel abgeschlossen',
      'story_all_complete': '🎬 Geschichte abgeschlossen — alle 5 Kapitel abgespielt',
      'story_paused_msg': 'Pausiert — Tippen Sie auf Play zum Fortsetzen',
    },
    'pt': {
      'nav_explore': 'Explorar',
      'nav_explore_sub': 'Mapa Interativo e Regiões',
      'nav_story': 'História',
      'nav_story_sub': 'Capítulos de Histórias Automatizados',
      'nav_settings': 'Configurações',
      'nav_settings_sub': 'Liquid Galaxy e Configuração',
      'drawer_title': 'Contador do Clima',
      'drawer_subtitle': 'Visualizador Liquid Galaxy',
      'lg_connected': 'LG Rig Conectado',
      'lg_disconnected': 'LG Rig Desconectado',
      'dark_theme': 'Tema Escuro',
      'settings_title': 'Configurações',
      'settings_sub': 'Configurar conexão com Liquid Galaxy, temas e opções',
      'sec_application': 'Aplicação',
      'sec_api_keys': 'Chaves de API',
      'sec_about': 'Sobre',
      'sec_lg_actions': 'AÇÕES DO LIQUID GALAXY',
      'sec_data_storage': 'DADOS E ARMAZENAMENTO',
      'tile_language': 'Idioma',
      'tile_theme': 'Modo de Tema',
      'theme_light': 'Modo Claro',
      'theme_dark': 'Modo Escuro',
      'theme_system': 'Padrão do Sistema',
      'tile_data_sources': 'Fontes de Dados',
      'tile_data_sources_sub': 'NASA GIBS, NOAA, IPCC',
      'data_sources_title': 'Fontes de Dados Climáticos',
      'data_sources_sub': 'Como recuperamos e renderizamos dados da Terra',
      'ds_data_provided': 'Dados Fornecidos',
      'ds_how_we_get_it': 'Como os Obtemos',
      'ds_nasa_gibs_desc': 'Imagens de satélite em alta resolução e sobreposições raster ambientais.',
      'ds_nasa_gibs_how': 'Busca camadas WMTS (EPSG:4326) em tempo real da NASA Earthdata e as formata em GroundOverlays KML dinâmicos.',
      'ds_noaa_desc': 'Anomalias históricas de temperatura, tendências do nível médio do mar e índice de gelo do NSIDC.',
      'ds_noaa_how': 'Consulta API de dados climáticos da NOAA (v2) e endpoints de Marés e Correntes, gerando séries temporais no Liquid Galaxy.',
      'ds_ipcc_desc': 'Projeções climáticas CMIP6 e cenários SSP (SSP1-2.6 a SSP5-8.5).',
      'ds_ipcc_how': 'Incorpora modelos do 6º Relatório do IPCC com marcadores multi-época e polígonos regionais.',
      'ds_openaq_desc': 'Dados globais em tempo real de qualidade do ar para PM2.5, PM10, NO2 e O3 superficial.',
      'ds_openaq_how': 'Chama a API REST v2 do OpenAQ para leituras atmosféricas ao vivo em megacidades mundiais.',
      'ds_gfw_desc': 'Alertas de desmatamento tropical, perda de cobertura florestal e monitoramento de queimadas.',
      'ds_gfw_how': 'Processa feeds CSV VIIRS da NASA FIRMS e dados Hansen/UMD exibidos diretamente nas telas do Liquid Galaxy.',
      'tile_networklink': 'Configurar NetworkLink',
      'tile_networklink_sub': 'Corrigir sincronização do Google Earth',
      'tile_kml_cache': 'Cache KML',
      'tile_kml_cache_sub': 'Pré-carregar conjuntos de dados KML',
      'tile_lg_diagnostics': 'Diagnósticos do LG',
      'tile_lg_diagnostics_sub': 'Verificação de sistema e portas',
      'tile_api_setup': 'Configuração de API',
      'tile_api_setup_sub': 'Chaves de IA Gemini e NOAA',
      'tile_about': 'Sobre o Storyteller',
      'tile_about_sub': 'GeSoC 2026 · Projeto Liquid Galaxy · v2.0.0',
      'btn_disconnect': 'Desconectar',
      'btn_connect_lg': 'Conectar ao LG Rig',
      'lg_status_connected': 'LG Rig · Conectado',
      'lg_status_disconnected': 'LG Rig · Desconectado',
      'about_description': 'Climate Change Storyteller é uma plataforma de visualização multi-telas para o Liquid Galaxy. Exibe camadas KML interativas e cronologias para contar a história do clima da Terra.',
      'about_org': 'Organização',
      'about_prog': 'Programa',
      'about_sys': 'Sistema Alvo',
      'about_tech': 'Tecnologia Principal',
      'btn_close': 'Fechar',
      'btn_cancel': 'Cancelar',
      'btn_delete': 'Excluir',
      'explore_title': 'Explorar Regiões Climáticas',
      'explore_sub': 'Toque num alfinete para abrir o balão na tela direita do LG',
      'cat_all': 'Todos',
      'cat_glaciers': 'Geleiras',
      'cat_sealevel': 'Nível do Mar',
      'cat_forests': 'Florestas',
      'cat_heat': 'Calor',
      'climate_regions': 'REGIÕES CLIMÁTICAS',
      'remove_all_added': 'Remover Todos Adicionados',
      'remove_all_title': 'Remover todos os locais adicionados?',
      'remove_all_confirm_desc': 'Tem certeza de que deseja remover todos os locais adicionados? Esta ação não pode ser desfeita.',
      'btn_remove_all': 'Remover Todos',
      'add_custom_region': 'Adicionar Região Personalizada',
      'all_locations_removed': 'Todos os locais adicionados foram removidos.',
      'badge_custom': 'Personalizado',
      'tap_fullscreen': 'Toque na imagem para tela cheia',
      'narration_generating': 'Gerando narrativa única de IA…',
      'narration_playing': 'Reproduzindo Narrativa de IA',
      'narration_paused': 'Narrativa Pausada',
      'narration_title': 'Narrativa do Storyteller de IA',
      'btn_stop_narration': 'Parar Narrativa',
      'btn_resume_narration': 'Retomar Narrativa',
      'btn_start_narration': 'Iniciar Narrativa',
      'time_slider_title': 'Controle de Tempo KML no LG (1850 – 2150)',
      'select_region_hint': 'Selecione uma região para ativar o controle de tempo',
      'btn_reload_kml': 'Recarregar KML',
      'btn_select_pin': 'Selecione um Alfinete',
      'btn_orbit': 'Órbita 3D',
      'btn_stop_orbit': 'Parar Órbita',
      'uploading_kml': 'Enviando KML para o LG Rig...',
      'slider_speed': 'Velocidade',
      'era_pre_industrial': 'Pré-industrial',
      'era_mid_century': 'Meados do Século',
      'era_late_century': 'Fim do Século',
      'era_present': 'Presente',
      'era_mid_projection': 'Projeção Média',
      'era_projected_2100': 'Projetado 2100',
      'story_mode_title': 'Modo História',
      'story_mode_sub': 'Apresentação automatizada para Liquid Galaxy',
      'story_progress': 'PROGRESSO DA HISTÓRIA',
      'chapters_title': 'Capítulos',
      'story_press_play': 'Pressione Play para começar a história',
      'story_playing': 'Reproduzindo',
      'story_paused': 'Pausado',
      'story_preparing': 'Preparando capítulo da história...',
      'ch_0_title': 'O Mundo Antes',
      'ch_0_sub': '1900 · Terra pré-industrial',
      'ch_1_title': 'O Grande Degelo',
      'ch_1_sub': '2026 · Círculo Ártico hoje',
      'ch_2_title': 'Florestas em Queda',
      'ch_2_sub': '2026 · Bacia Amazônica',
      'ch_3_title': 'Águas Crescentes',
      'ch_3_sub': '2100 · Maldivas',
      'ch_4_title': 'Uma Escolha Resta',
      'ch_4_sub': '2100 · Ilhas do Pacífico',
      'btn_clear_kml': 'Limpar KML',
      'kml_cleared_msg': 'Todos os KMLs removidos do Liquid Galaxy de uma vez!',
      'live_climate_alerts': 'ALERTAS CLIMÁTICOS EM TEMPO REAL',
      'btn_refresh': 'Atualizar',
      'loading_alerts': 'Carregando alertas climáticos...',
      'climate_layers': 'Camadas Climáticas (KML)',
      'btn_fly_to_region': 'Voar para a Região',
      'btn_orbit_region': 'Orbitar Região (360°)',
      'not_connected_lg': 'Não conectado ao LG Rig',
      'status_viewing': 'Visualizando no LG',
      'status_send_to_lg': 'Enviar para LG',
      'onboarding_next': 'Próximo',
      'onboarding_get_started': 'Começar',
      'onboarding_skip': 'Pular',
      'story_done': 'Concluído',
      'story_chapter': 'Capítulo',
      'story_progress_chapter': 'Progresso do capítulo',
      'story_chapters_count': '5 Capítulos · Reprodução automática',
      'theme_light_sub': 'Modo claro limpo',
      'theme_dark_sub': 'Modo escuro padrão',
      'theme_system_sub': 'Corresponder ao sistema',
      'btn_back': 'Voltar',
      'story_syncing': 'Sincronizando',
      'story_speaking': 'Narrando…',
      'story_chapter_complete': '✓ Capítulo concluído',
      'story_all_complete': '🎬 História concluída — todos os 5 capítulos reproduzidos',
      'story_paused_msg': 'Pausado — toque em Reproduzir para continuar',
    },
    'it': {
      'nav_explore': 'Esplora',
      'nav_explore_sub': 'Mappa Interattiva e Regioni',
      'nav_story': 'Storia',
      'nav_story_sub': 'Capitoli della Storia Automatizzati',
      'nav_settings': 'Impostazioni',
      'nav_settings_sub': 'Liquid Galaxy e Configurazione',
      'drawer_title': 'Narratore Climatico',
      'drawer_subtitle': 'Visualizzatore Liquid Galaxy',
      'lg_connected': 'LG Rig Connesso',
      'lg_disconnected': 'LG Rig Disconnesso',
      'dark_theme': 'Tema Scuro',
      'settings_title': 'Impostazioni',
      'settings_sub': 'Configura connessione Liquid Galaxy, temi e opzioni',
      'sec_application': 'Applicazione',
      'sec_api_keys': 'Chiavi API',
      'sec_about': 'Informazioni',
      'sec_lg_actions': 'AZIONI LIQUID GALAXY',
      'sec_data_storage': 'DATI E ARCHIVIAZIONE',
      'tile_language': 'Lingua',
      'tile_theme': 'Modalità Tema',
      'theme_light': 'Modalità Chiara',
      'theme_dark': 'Modalità Scura',
      'theme_system': 'Predefinito di Sistema',
      'tile_data_sources': 'Fonti di Dati',
      'tile_data_sources_sub': 'NASA GIBS, NOAA, IPCC',
      'data_sources_title': 'Fonti di Dati Climatici',
      'data_sources_sub': 'Come raccogliamo e visualizziamo i dati terrestri',
      'ds_data_provided': 'Dati Forniti',
      'ds_how_we_get_it': 'Come li Otteniamo',
      'ds_nasa_gibs_desc': 'Tile di immagini satellitari ad alta risoluzione e overlay raster ambientali.',
      'ds_nasa_gibs_how': 'Recupera layer WMTS (EPSG:4326) in tempo reale da NASA Earthdata e li formatta in GroundOverlay KML dinamici.',
      'ds_noaa_desc': 'Anomalie storiche di temperatura, trend del livello del mare e indice dei ghiacci NSIDC.',
      'ds_noaa_how': 'Interroga API NOAA (v2) ed endpoint Maree e Correnti, generando serie temporali su Liquid Galaxy.',
      'ds_ipcc_desc': 'Proiezioni climatiche CMIP6 e scenari SSP (SSP1-2.6 a SSP5-8.5).',
      'ds_ipcc_how': 'Incorpora modelli del 6° Rapporto IPCC con segnaposto multi-epoca e poligoni regionali.',
      'ds_openaq_desc': 'Dati globali in tempo reale sulla qualità dell\'aria (PM2.5, PM10, NO2, O3).',
      'ds_openaq_how': 'Interroga API REST OpenAQ v2 per rilevamenti in tempo reale nelle megalopoli mondiali.',
      'ds_gfw_desc': 'Allarmi deforestazione tropicale, perdita di copertura arborea e incendi attivi.',
      'ds_gfw_how': 'Elabora dati NASA FIRMS VIIRS e dati Hansen/UMD mostrati sugli schermi Liquid Galaxy.',
      'tile_networklink': 'Configura NetworkLink',
      'tile_networklink_sub': 'Risolvi sincronizzazione Google Earth',
      'tile_kml_cache': 'Cache KML',
      'tile_kml_cache_sub': 'Precarica set di dati KML',
      'tile_lg_diagnostics': 'Diagnostica LG',
      'tile_lg_diagnostics_sub': 'Controllo di sistema e porte',
      'tile_api_setup': 'Configurazione API',
      'tile_api_setup_sub': 'Chiavi IA Gemini e NOAA',
      'tile_about': 'Informazioni su Storyteller',
      'tile_about_sub': 'GeSoC 2026 · Progetto Liquid Galaxy · v2.0.0',
      'btn_disconnect': 'Disconnetti',
      'btn_connect_lg': 'Connetti a LG Rig',
      'lg_status_connected': 'LG Rig · Connesso',
      'lg_status_disconnected': 'LG Rig · Disconnesso',
      'about_description': 'Climate Change Storyteller è una piattaforma di visualizzazione multi-schermo per Liquid Galaxy. Mostra livelli KML interattivi e cronologie per raccontare la storia del clima che cambia.',
      'about_org': 'Organizzazione',
      'about_prog': 'Programma',
      'about_sys': 'Sistema Target',
      'about_tech': 'Tecnologia Principale',
      'btn_close': 'Chiudi',
      'btn_cancel': 'Annulla',
      'btn_delete': 'Elimina',
      'explore_title': 'Esplora Regioni Climatiche',
      'explore_sub': 'Tocca un punto per aprire il fumetto sullo schermo destro di LG',
      'cat_all': 'Tutti',
      'cat_glaciers': 'Ghiacciai',
      'cat_sealevel': 'Livello del Mare',
      'cat_forests': 'Foreste',
      'cat_heat': 'Calore',
      'climate_regions': 'REGIONI CLIMATICHE',
      'remove_all_added': 'Rimuovi Tutti gli Aggiunti',
      'remove_all_title': 'Rimuovere tutte le posizioni aggiunte?',
      'remove_all_confirm_desc': 'Sei sicuro di voler rimuovere tutte le posizioni aggiunte? Questa azione non può essere annullata.',
      'btn_remove_all': 'Rimuovi Tutto',
      'add_custom_region': 'Aggiungi Regione Personalizzata',
      'all_locations_removed': 'Tutte le posizioni aggiunte sono state rimosse.',
      'badge_custom': 'Personalizzato',
      'tap_fullscreen': 'Tocca l\'immagine per schermo intero',
      'narration_generating': 'Generazione narrazione IA unica…',
      'narration_playing': 'Riproduzione Narrazione IA',
      'narration_paused': 'Narrazione in Pausa',
      'narration_title': 'Narrazione IA Storyteller',
      'btn_stop_narration': 'Ferma Narrazione',
      'btn_resume_narration': 'Riprendi Narrazione',
      'btn_start_narration': 'Avvia Narrazione',
      'time_slider_title': 'Cursore Temporale KML LG (1850 – 2150)',
      'select_region_hint': 'Seleziona una regione per attivare il cursore temporale',
      'btn_reload_kml': 'Ricarica KML',
      'btn_select_pin': 'Seleziona un Punto',
      'btn_orbit': 'Orbita 3D',
      'btn_stop_orbit': 'Ferma Orbita',
      'uploading_kml': 'Caricamento KML su LG Rig...',
      'slider_speed': 'Velocità',
      'era_pre_industrial': 'Pre-industriale',
      'era_mid_century': 'Metà Secolo',
      'era_late_century': 'Fine Secolo',
      'era_present': 'Presente',
      'era_mid_projection': 'Proiezione Media',
      'era_projected_2100': 'Proiezione 2100',
      'story_mode_title': 'Modalità Storia',
      'story_mode_sub': 'Presentazione automatizzata per Liquid Galaxy',
      'story_progress': 'PROGRESSO DELLA STORIA',
      'chapters_title': 'Capitoli',
      'story_press_play': 'Premi Play per iniziare la storia',
      'story_playing': 'In riproduzione',
      'story_paused': 'In pausa',
      'story_preparing': 'Preparazione capitolo...',
      'ch_0_title': 'Il Mondo di Prima',
      'ch_0_sub': '1900 · Terra pre-industriale',
      'ch_1_title': 'Il Grande Disgelo',
      'ch_1_sub': '2026 · Circolo Polare Artico oggi',
      'ch_2_title': 'Foreste che Cadono',
      'ch_2_sub': '2026 · Bacino dell\'Amazzonia',
      'ch_3_title': 'Acque Crescenti',
      'ch_3_sub': '2100 · Maldive',
      'ch_4_title': 'Rimane una Scelta',
      'ch_4_sub': '2100 · Isole del Pacifico',
      'btn_clear_kml': 'Cancella KML',
      'kml_cleared_msg': 'Tutti i KML rimossi da Liquid Galaxy in un colpo solo!',
      'live_climate_alerts': 'ALLERTI CLIMATICI IN DIRETTA',
      'btn_refresh': 'Aggiorna',
      'loading_alerts': 'Caricamento allarmi climatici...',
      'climate_layers': 'Strati Climatici (KML)',
      'btn_fly_to_region': 'Vola alla Regione',
      'btn_orbit_region': 'Orbita Regione (360°)',
      'not_connected_lg': 'Non connesso a LG Rig',
      'status_viewing': 'Visualizzazione su LG',
      'status_send_to_lg': 'Invia a LG',
      'onboarding_next': 'Avanti',
      'onboarding_get_started': 'Inizia',
      'onboarding_skip': 'Salta',
      'story_done': 'Fatto',
      'story_chapter': 'Capitolo',
      'story_progress_chapter': 'Progresso del capitolo',
      'story_chapters_count': '5 Capitoli · Riproduzione automatica',
      'theme_light_sub': 'Modalità chiara pulita',
      'theme_dark_sub': 'Modalità scura predefinita',
      'theme_system_sub': 'Segui impostazioni di sistema',
      'btn_back': 'Indietro',
      'story_syncing': 'Sincronizzazione',
      'story_speaking': 'Voce narrante in corso…',
      'story_chapter_complete': '✓ Capitolo completato',
      'story_all_complete': '🎬 Storia completata — tutti i 5 capitoli riprodotti',
      'story_paused_msg': 'In pausa — tocca Riproduci per riprendere',
    },
    'hi': {
      'nav_explore': 'अन्वेषण',
      'nav_explore_sub': 'इंटरएक्टिव मानचित्र और क्षेत्र',
      'nav_story': 'कहानी',
      'nav_story_sub': 'स्वचालित कहानी अध्याय',
      'nav_settings': 'सेटिंग्स',
      'nav_settings_sub': 'लिक्विड गैलेक्सी और सेटअप',
      'drawer_title': 'जलवायु कथावाचक',
      'drawer_subtitle': 'लिक्विड गैलेक्सी विज़ुअलाइज़र',
      'lg_connected': 'एलजी रिग जुड़ा हुआ है',
      'lg_disconnected': 'एलजी रिग डिस्कनेक्ट है',
      'dark_theme': 'डार्क थीम',
      'settings_title': 'सेटिंग्स',
      'settings_sub': 'लिक्विड गैलेक्सी कनेक्शन, थीम और विकल्प कॉन्फ़िगर करें',
      'sec_application': 'अनुप्रयोग',
      'sec_api_keys': 'एपीआई कुंजियाँ',
      'sec_about': 'के बारे में',
      'sec_lg_actions': 'लिक्विड गैलेक्सी क्रियाएं',
      'sec_data_storage': 'डेटा और भंडारण',
      'tile_language': 'भाषा',
      'tile_theme': 'थीम मोड',
      'theme_light': 'लाइट मोड',
      'theme_dark': 'डार्क मोड',
      'theme_system': 'सिस्टम डिफ़ॉल्ट',
      'tile_data_sources': 'डेटा स्रोत',
      'tile_data_sources_sub': 'नासा गिब्स, नोआ, आईपीसीसी',
      'data_sources_title': 'जलवायु डेटा स्रोत',
      'data_sources_sub': 'हम पृथ्वी डेटा कैसे प्राप्त और प्रस्तुत करते हैं',
      'ds_data_provided': 'प्रदान किया गया डेटा',
      'ds_how_we_get_it': 'हम इसे कैसे प्राप्त करते हैं',
      'ds_nasa_gibs_desc': 'उच्च-रिज़ॉल्यूशन उपग्रह इमेजरी टाइल्स और पर्यावरण रेखापुंज ओवरले।',
      'ds_nasa_gibs_how': 'नासा अर्थडेटा सर्वर से सीधे वास्तविक समय WMTS टाइल परतें प्राप्त करता है और उन्हें डायनामिक KML ग्राउंडओवरले में प्रारूपित करता है।',
      'ds_noaa_desc': 'ऐतिहासिक तापमान विसंगतियाँ, समुद्र स्तर के रुझान और एनएसआईडीसी बर्फ सूचकांक।',
      'ds_noaa_how': 'नोआ क्लाइमेट डेटा ऑनलाइन एपीआई (v2) को क्वेरी करता है और लिक्विड गैलेक्सी पर टाइम सीरीज़ जनरेट करता है।',
      'ds_ipcc_desc': 'CMIP6 जलवायु अनुमान और SSP परिदृश्य (SSP1-2.6 से SSP5-8.5)।',
      'ds_ipcc_how': 'आईपीसीसी 6वीं मूल्यांकन रिपोर्ट डेटासेट मॉडल को एम्बेड करता है।',
      'ds_openaq_desc': 'पीएम2.5, पीएम10, एनओ2 और ओ3 के लिए वैश्विक वास्तविक समय वायु गुणवत्ता डेटा।',
      'ds_openaq_how': 'वैश्विक महानगरों में लाइव वायुमंडलीय रीडिंग के लिए OpenAQ REST API v2 को कॉल करता है।',
      'ds_gfw_desc': 'उष्णकटिबंधीय वनों की कटाई अलर्ट, कैनोपी कवर का नुकसान और सक्रिय आग ट्रैकिंग।',
      'ds_gfw_how': 'नासा फर्म्स वीआईआईआरएस सक्रिय आग डेटा को सीधे लिक्विड गैलेक्सी स्क्रीन पर प्रस्तुत करता है।',
      'tile_networklink': 'नेटवर्कलिंक सेटअप करें',
      'tile_networklink_sub': 'गूगल अर्थ सिंक ठीक करें',
      'tile_kml_cache': 'केएमएल कैश',
      'tile_kml_cache_sub': 'केएमएल डेटासेट पहले से लोड करें',
      'tile_lg_diagnostics': 'एलजी डायग्नोस्टिक्स',
      'tile_lg_diagnostics_sub': 'सिस्टम और पोर्ट जांच',
      'tile_api_setup': 'एपीआई सेटअप',
      'tile_api_setup_sub': 'जेमिनी एआई और नोआ कुंजियां',
      'tile_about': 'स्टोरीटेलर के बारे में',
      'tile_about_sub': 'GeSoC 2026 · लिक्विड गैलेक्सी प्रोजेक्ट · v2.0.0',
      'btn_disconnect': 'डिस्कनेक्ट करें',
      'btn_connect_lg': 'एलजी रिग से कनेक्ट करें',
      'lg_status_connected': 'एलजी रिग · जुड़ा हुआ',
      'lg_status_disconnected': 'एलजी रिग · डिस्कनेक्ट',
      'about_description': 'क्लाइमेट चेंज स्टोरीटेलर लिक्विड गैलेक्सी के लिए एक मल्टी-स्क्रीन विज़ुअलाइज़ेशन प्लेटफ़ॉर्म है। यह पृथ्वी की बदलती जलवायु की कहानी बताने के लिए इंटरैक्टिव केएमएल परतों और समयरेखा को प्रदर्शित करता है।',
      'about_org': 'संगठन',
      'about_prog': 'कार्यक्रम',
      'about_sys': 'लक्षित प्रणाली',
      'about_tech': 'मुख्य तकनीक',
      'btn_close': 'बंद करें',
      'btn_cancel': 'रद्द करें',
      'btn_delete': 'हटाएं',
      'explore_title': 'जलवायु क्षेत्रों का अन्वेषण करें',
      'explore_sub': 'दाएँ एलजी स्क्रीन पर विवरण देखने के लिए मानचित्र पर पिन टैप करें',
      'cat_all': 'सभी',
      'cat_glaciers': 'हिमनद',
      'cat_sealevel': 'समुद्र स्तर',
      'cat_forests': 'वन',
      'cat_heat': 'अत्यधिक ताप',
      'climate_regions': 'जलवायु क्षेत्र',
      'remove_all_added': 'सभी जोड़े गए हटाएं',
      'remove_all_title': 'क्या सभी जोड़े गए स्थान हटाएँ?',
      'remove_all_confirm_desc': 'क्या आप निश्चित रूप से सभी उपयोगकर्ता द्वारा जोड़े गए स्थानों को हटाना चाहते हैं? यह क्रिया पूर्ववत नहीं की जा सकती।',
      'btn_remove_all': 'सभी हटाएं',
      'add_custom_region': 'कस्टम क्षेत्र जोड़ें',
      'all_locations_removed': 'सभी जोड़े गए स्थान हटा दिए गए।',
      'badge_custom': 'कस्टम',
      'tap_fullscreen': 'पूर्ण-स्क्रीन में देखने के लिए छवि पर टैप करें',
      'narration_generating': 'अद्वितीय एआई विवरण तैयार किया जा रहा है…',
      'narration_playing': 'एआई विवरण चल रहा है',
      'narration_paused': 'विवरण रुका हुआ',
      'narration_title': 'एआई स्टोरीटेलर विवरण',
      'btn_stop_narration': 'विवरण रोकें',
      'btn_resume_narration': 'विवरण जारी रखें',
      'btn_start_narration': 'विवरण शुरू करें',
      'time_slider_title': 'एलजी केएमएल समय स्लाइडर (1850 – 2150)',
      'select_region_hint': 'एलजी समय स्लाइडर सक्रिय करने के लिए एक जलवायु क्षेत्र चुनें',
      'btn_reload_kml': 'केएमएल पुनः लोड करें',
      'btn_select_pin': 'एक क्षेत्र पिन चुनें',
      'btn_orbit': '3D कक्षा',
      'btn_stop_orbit': 'कक्षा रोकें',
      'uploading_kml': 'एलजी रिग पर केएमएल अपलोड हो रहा है...',
      'slider_speed': 'गति',
      'era_pre_industrial': 'पूर्व-औद्योगिक',
      'era_mid_century': 'मध्य-शताब्दी',
      'era_late_century': 'उत्तर-शताब्दी',
      'era_present': 'वर्तमान',
      'era_mid_projection': 'मध्य प्रक्षेपण',
      'era_projected_2100': '2100 का अनुमान',
      'story_mode_title': 'स्टोरी मोड',
      'story_mode_sub': 'लिक्विड गैलेक्सी के लिए स्वचालित प्रस्तुति',
      'story_progress': 'कहानी की प्रगति',
      'chapters_title': 'अध्याय',
      'story_press_play': 'कहानी शुरू करने के लिए प्ले दबाएं',
      'story_playing': 'चल रहा है',
      'story_paused': 'रुका हुआ',
      'story_preparing': 'कहानी अध्याय तैयार हो रहा है...',
      'ch_0_title': 'पहले की दुनिया',
      'ch_0_sub': '1900 · पूर्व-औद्योगिक पृथ्वी',
      'ch_1_title': 'महा पिघलाव',
      'ch_1_sub': '2026 · आज आर्कटिक वृत्त',
      'ch_2_title': 'गिरते हुए जंगल',
      'ch_2_sub': '2026 · अमेज़न बेसिन',
      'ch_3_title': 'बढ़ता हुआ जलस्तर',
      'ch_3_sub': '2100 · मालदीव',
      'ch_4_title': 'एक विकल्प बाकी है',
      'ch_4_sub': '2100 · प्रशांत द्वीप समूह',
      'btn_clear_kml': 'केएमएल साफ करें',
      'kml_cleared_msg': 'लिक्विड गैलेक्सी से सभी केएमएल एक साथ हटा दिए गए!',
      'live_climate_alerts': 'लाइव जलवायु अलर्ट',
      'btn_refresh': 'ताज़ा करें',
      'loading_alerts': 'जलवायु अलर्ट लोड हो रहे हैं...',
      'climate_layers': 'जलवायु परतें (KML)',
      'btn_fly_to_region': 'क्षेत्र पर उड़ें',
      'btn_orbit_region': 'क्षेत्र की 360° परिक्रमा',
      'not_connected_lg': 'एलजी रिग से जुड़ा नहीं है',
      'status_viewing': 'एलजी पर देख रहे हैं',
      'status_send_to_lg': 'एलजी को भेजें',
      'onboarding_next': 'आगे',
      'onboarding_get_started': 'शुरू करें',
      'onboarding_skip': 'छोड़ें',
      'story_done': 'पूर्ण',
      'story_chapter': 'अध्याय',
      'story_progress_chapter': 'अध्याय प्रगति',
      'story_chapters_count': '5 अध्याय · स्वतः प्ले',
      'theme_light_sub': 'साफ लाइट मोड',
      'theme_dark_sub': 'डिफ़ॉल्ट डार्क मोड',
      'theme_system_sub': 'सिस्टम सेटिंग से मिलान करें',
      'btn_back': 'पीछे',
      'story_syncing': 'सिंक हो रहा है',
      'story_speaking': 'कथा वाचन जारी है…',
      'story_chapter_complete': '✓ अध्याय पूर्ण',
      'story_all_complete': '🎬 कहानी पूर्ण — सभी 5 अध्याय समाप्त',
      'story_paused_msg': 'रोका गया — फिर से शुरू करने के लिए प्ले दबाएं',
    },
    'ja': {
      'nav_explore': '探索',
      'nav_explore_sub': 'インタラクティブマップと地域',
      'nav_story': 'ストーリー',
      'nav_story_sub': '自動ストーリーチャプター',
      'nav_settings': '設定',
      'nav_settings_sub': 'Liquid Galaxyとセットアップ',
      'drawer_title': 'クライメートストーリーテラー',
      'drawer_subtitle': 'Liquid Galaxy ビジュアライザー',
      'lg_connected': 'LG Rig 接続済み',
      'lg_disconnected': 'LG Rig 未接続',
      'dark_theme': 'ダークテーマ',
      'settings_title': '設定',
      'settings_sub': 'Liquid Galaxy接続、テーマ、オプションを設定',
      'sec_application': 'アプリケーション',
      'sec_api_keys': 'APIキー',
      'sec_about': '情報',
      'sec_lg_actions': 'LIQUID GALAXY アクション',
      'sec_data_storage': 'データとストレージ',
      'tile_language': '言語',
      'tile_theme': 'テーマモード',
      'theme_light': 'ライトモード',
      'theme_dark': 'ダークモード',
      'theme_system': 'システムデフォルト',
      'tile_data_sources': 'データソース',
      'tile_data_sources_sub': 'NASA GIBS, NOAA, IPCC',
      'data_sources_title': '気候データソース',
      'data_sources_sub': '地球データの取得および表示方法',
      'ds_data_provided': '提供データ',
      'ds_how_we_get_it': '取得方法',
      'ds_nasa_gibs_desc': '高解像度衛星画像タイルと環境ラスターオーバーレイ。',
      'ds_nasa_gibs_how': 'NASA EarthdataからWMTS (EPSG:4326) タイルを直接取得し、動的KMLグラウンドオーバーレイにフォーマットします。',
      'ds_noaa_desc': '過去の気温異常、平均海面水位の傾向、およびNSIDC海氷指数。',
      'ds_noaa_how': 'NOAAのオンライン気候データAPIと潮汐RESTエンドポイントを照会し、Liquid Galaxy上に時系列データを生成します。',
      'ds_ipcc_desc': 'CMIP6気候予測およびSSPシナリオ (SSP1-2.6〜SSP5-8.5)。',
      'ds_ipcc_how': 'IPCC第6次評価報告書データセットモデルを組み込んでいます。',
      'ds_openaq_desc': 'PM2.5、PM10、NO2、地上O3のリアルタイム大気質データ。',
      'ds_openaq_how': '世界の大都市の大気測定値を取得するためOpenAQ REST API v2を呼び出します。',
      'ds_gfw_desc': '熱帯林伐採アラート、樹冠被覆減少、および活発な火災追跡。',
      'ds_gfw_how': 'NASA FIRMS VIIRSアクティブ火災データをLiquid Galaxy画面に直接描画します。',
      'tile_networklink': 'NetworkLinkのセットアップ',
      'tile_networklink_sub': 'Google Earthの同期を修正',
      'tile_kml_cache': 'KMLキャッシュ',
      'tile_kml_cache_sub': 'KMLデータセットの事前読み込み',
      'tile_lg_diagnostics': 'LG診断',
      'tile_lg_diagnostics_sub': 'システムとポートのチェック',
      'tile_api_setup': 'API設定',
      'tile_api_setup_sub': 'Gemini AI & NOAAキー',
      'tile_about': 'Storytellerについて',
      'tile_about_sub': 'GeSoC 2026 · Liquid Galaxy プロジェクト · v2.0.0',
      'btn_disconnect': '切断',
      'btn_connect_lg': 'LG Rigに接続',
      'lg_status_connected': 'LG Rig · 接続済み',
      'lg_status_disconnected': 'LG Rig · 未接続',
      'about_description': 'Climate Change Storytellerは、Liquid Galaxy向けマルチスクリーン視覚化プラットフォームです。インタラクティブなKMLレイヤーとタイムラインを表示して、地球の気候変動のストーリーを伝えます。',
      'about_org': '組織',
      'about_prog': 'プログラム',
      'about_sys': '対象システム',
      'about_tech': 'コア技術',
      'btn_close': '閉じる',
      'btn_cancel': 'キャンセル',
      'btn_delete': '削除',
      'explore_title': '気候地域の探索',
      'explore_sub': '地図のピンをタップしてLG右画面に説明バルーンを表示',
      'cat_all': 'すべて',
      'cat_glaciers': '氷河',
      'cat_sealevel': '海水面',
      'cat_forests': '森林',
      'cat_heat': '猛暑',
      'climate_regions': '気候地域',
      'remove_all_added': '追加した場所をすべて削除',
      'remove_all_title': '追加したすべての場所を削除しますか？',
      'remove_all_confirm_desc': '追加したすべての場所を削除してもよろしいですか？この操作は元に戻せません。',
      'btn_remove_all': 'すべて削除',
      'add_custom_region': 'カスタム地域を追加',
      'all_locations_removed': '追加した場所がすべて削除されました。',
      'badge_custom': 'カスタム',
      'tap_fullscreen': '画像をタップして全画面表示',
      'narration_generating': '独自のAIナレーションを生成中…',
      'narration_playing': 'AIナレーション再生中',
      'narration_paused': 'ナレーション一時停止',
      'narration_title': 'AIストーリーテラーのナレーション',
      'btn_stop_narration': 'ナレーション停止',
      'btn_resume_narration': 'ナレーション再開',
      'btn_start_narration': 'ナレーション開始',
      'time_slider_title': 'LG KML タイムスライダー (1850 – 2150)',
      'select_region_hint': 'LGタイムスライダーを有効にするには気候地域を選択してください',
      'btn_reload_kml': 'KMLを再読み込み',
      'btn_select_pin': '地域ピンを選択',
      'btn_orbit': '3Dオービット',
      'btn_stop_orbit': 'オービット停止',
      'uploading_kml': 'LG RigにKMLをアップロード中...',
      'slider_speed': '速度',
      'era_pre_industrial': '産業革命前',
      'era_mid_century': '20世紀半ば',
      'era_late_century': '20世紀末',
      'era_present': '現在',
      'era_mid_projection': '中期予測',
      'era_projected_2100': '2100年予測',
      'story_mode_title': 'ストーリーモード',
      'story_mode_sub': 'Liquid Galaxy用自動プレゼンテーション',
      'story_progress': 'ストーリーの進行状況',
      'chapters_title': 'チャプター',
      'story_press_play': '再生を押してストーリーを開始',
      'story_playing': '再生中',
      'story_paused': '一時停止中',
      'story_preparing': 'チャプターを準備中...',
      'ch_0_title': 'かつての世界',
      'ch_0_sub': '1900年 · 産業革命前の地球',
      'ch_1_title': '大いなる融解',
      'ch_1_sub': '2026年 · 今日の北極圏',
      'ch_2_title': '失われゆく森林',
      'ch_2_sub': '2026年 · アマゾン盆地',
      'ch_3_title': '上昇する海水',
      'ch_3_sub': '2100年 · モルディブ',
      'ch_4_title': '残された選択肢',
      'ch_4_sub': '2100年 · 太平洋諸島',
      'btn_clear_kml': 'KMLを消去',
      'kml_cleared_msg': 'すべてのKMLがLiquid Galaxyから一度に消去されました！',
      'live_climate_alerts': 'ライブ気候アラート',
      'btn_refresh': '更新',
      'loading_alerts': '気候アラートを読み込み中...',
      'climate_layers': '気候レイヤー (KML)',
      'btn_fly_to_region': '地域へフライ',
      'btn_orbit_region': '地域を360°オービット',
      'not_connected_lg': 'LG Rigに接続されていません',
      'status_viewing': 'LGで表示中',
      'status_send_to_lg': 'LGに送信',
      'onboarding_next': '次へ',
      'onboarding_get_started': 'はじめる',
      'onboarding_skip': 'スキップ',
      'story_done': '完了',
      'story_chapter': '章',
      'story_progress_chapter': '章の進捗',
      'story_chapters_count': '5つの章 · 自動再生',
      'theme_light_sub': 'クリーンなライトモード',
      'theme_dark_sub': 'デフォルトのダークモード',
      'theme_system_sub': 'システム設定に合わせる',
      'btn_back': '戻る',
      'story_syncing': '同期中',
      'story_speaking': 'ナレーション音声再生中…',
      'story_chapter_complete': '✓ 章が完了しました',
      'story_all_complete': '🎬 ストーリー完了 — 全5章を再生しました',
      'story_paused_msg': '一時停止中 — 再生をタップして再開',
    },
    'zh': {
      'nav_explore': '探索',
      'nav_explore_sub': '交互式地图与区域',
      'nav_story': '故事',
      'nav_story_sub': '自动化故事章节',
      'nav_settings': '设置',
      'nav_settings_sub': '液态银河与配置',
      'drawer_title': '气候故事讲述者',
      'drawer_subtitle': '液态银河可视化器',
      'lg_connected': '液态银河已连接',
      'lg_disconnected': '液态银河未连接',
      'dark_theme': '深色模式',
      'settings_title': '设置',
      'settings_sub': '配置液态银河连接、主题与选项',
      'sec_application': '应用设置',
      'sec_api_keys': 'API密钥',
      'sec_about': '关于',
      'sec_lg_actions': '液态银河操作',
      'sec_data_storage': '数据与存储',
      'tile_language': '语言',
      'tile_theme': '主题模式',
      'theme_light': '浅色模式',
      'theme_dark': '深色模式',
      'theme_system': '系统默认',
      'tile_data_sources': '数据源',
      'tile_data_sources_sub': 'NASA GIBS, NOAA, IPCC',
      'data_sources_title': '气候数据源',
      'data_sources_sub': '我们如何检索并渲染地球数据',
      'ds_data_provided': '提供的数据',
      'ds_how_we_get_it': '获取方式',
      'ds_nasa_gibs_desc': '高分辨率卫星影像瓦片与环境栅格图层。',
      'ds_nasa_gibs_how': '直接从 NASA Earthdata 服务器获取实时 WMTS 瓦片图层并格式化为动态 KML GroundOverlay。',
      'ds_noaa_desc': '历史气温异常、平均海平面趋势以及 NSIDC 海冰指数。',
      'ds_noaa_how': '查询 NOAA 在线气候数据 API (v2) 及潮汐 REST 端点，在液态银河上生成时间序列地标。',
      'ds_ipcc_desc': 'CMIP6 气候预估与 SSP 情景 (SSP1-2.6 至 SSP5-8.5)。',
      'ds_ipcc_how': '内嵌 IPCC 第六次评估报告模型，具备多年份地标与区域多边形边界。',
      'ds_openaq_desc': '全球实时 PM2.5、PM10、NO2 及地面臭氧空气质量数据。',
      'ds_openaq_how': '调用 OpenAQ REST API v2 获取全球大都市的实时大气读数。',
      'ds_gfw_desc': '热带森林砍伐预警、林冠损失及活跃火点跟踪。',
      'ds_gfw_how': '解析 NASA FIRMS VIIRS 活跃火点 CSV 并在液态银河屏幕上直接渲染。',
      'tile_networklink': '配置网络链接',
      'tile_networklink_sub': '修复 Google 地球同步',
      'tile_kml_cache': 'KML缓存',
      'tile_kml_cache_sub': '预加载 KML 数据集',
      'tile_lg_diagnostics': 'LG诊断',
      'tile_lg_diagnostics_sub': '系统与端口检查',
      'tile_api_setup': 'API配置',
      'tile_api_setup_sub': 'Gemini AI 与 NOAA 密钥',
      'tile_about': '关于本应用',
      'tile_about_sub': 'GeSoC 2026 · 液态银河项目 · v2.0.0',
      'btn_disconnect': '断开连接',
      'btn_connect_lg': '连接至液态银河',
      'lg_status_connected': '液态银河 · 已连接',
      'lg_status_disconnected': '液态银河 · 未连接',
      'about_description': 'Climate Change Storyteller 是适用于液态银河（Liquid Galaxy）的多屏可视化平台。它通过交互式 KML 图层和时间线，向人们讲述地球气候变化的故事。',
      'about_org': '组织',
      'about_prog': '项目',
      'about_sys': '目标系统',
      'about_tech': '核心技术',
      'btn_close': '关闭',
      'btn_cancel': '取消',
      'btn_delete': '删除',
      'explore_title': '探索气候区域',
      'explore_sub': '点击地图上的图钉以在最右侧LG屏幕上自动打开说明气泡',
      'cat_all': '全部',
      'cat_glaciers': '冰川',
      'cat_sealevel': '海平面',
      'cat_forests': '森林',
      'cat_heat': '高温',
      'climate_regions': '气候区域',
      'remove_all_added': '删除所有添加的位置',
      'remove_all_title': '删除所有添加的位置？',
      'remove_all_confirm_desc': '您确定要删除所有用户添加的位置吗？此操作无法撤消。',
      'btn_remove_all': '删除全部',
      'add_custom_region': '添加自定义区域',
      'all_locations_removed': '已删除所有用户添加的位置。',
      'badge_custom': '自定义',
      'tap_fullscreen': '点击图片以全屏查看',
      'narration_generating': '正在生成独有的AI解说…',
      'narration_playing': '正在播放AI解说',
      'narration_paused': '解说已暂停',
      'narration_title': 'AI故事解说',
      'btn_stop_narration': '停止解说',
      'btn_resume_narration': '恢复解说',
      'btn_start_narration': '开始解说',
      'time_slider_title': '液态银河 KML 时间滑块 (1850 – 2150)',
      'select_region_hint': '请选择气候区域以激活时间滑块',
      'btn_reload_kml': '重新加载 KML',
      'btn_select_pin': '请选择区域图钉',
      'btn_orbit': '3D环绕',
      'btn_stop_orbit': '停止环绕',
      'uploading_kml': '正在上传 KML 到液态银河...',
      'slider_speed': '速度',
      'era_pre_industrial': '前工业化',
      'era_mid_century': '20世纪中叶',
      'era_late_century': '20世纪末',
      'era_present': '现今',
      'era_mid_projection': '中期预测',
      'era_projected_2100': '2100年预测',
      'story_mode_title': '故事模式',
      'story_mode_sub': '适用于液态银河的自动演示',
      'story_progress': '故事进度',
      'chapters_title': '章节',
      'story_press_play': '点击播放以开始故事',
      'story_playing': '正在播放',
      'story_paused': '已暂停',
      'story_preparing': '正在准备故事章节...',
      'ch_0_title': '过去的世界',
      'ch_0_sub': '1900 · 工业化前的地球',
      'ch_1_title': '冰川大融化',
      'ch_1_sub': '2026 · 今天的北极圈',
      'ch_2_title': '森林消逝',
      'ch_2_sub': '2026 · 亚马逊流域',
      'ch_3_title': '水位上升',
      'ch_3_sub': '2100 · 马尔代夫',
      'ch_4_title': '仍有选择',
      'ch_4_sub': '2100 · 太平洋群岛',
      'btn_clear_kml': '清除 KML',
      'kml_cleared_msg': '已一次性从液态银河中清除所有 KML！',
      'live_climate_alerts': '实时气候预警',
      'btn_refresh': '刷新',
      'loading_alerts': '正在加载气候警报...',
      'climate_layers': '气候图层 (KML)',
      'btn_fly_to_region': '飞至该区域',
      'btn_orbit_region': '360°环绕该区域',
      'not_connected_lg': '未连接至液态银河',
      'status_viewing': '正在液态银河上查看',
      'status_send_to_lg': '发送至液态银河',
      'onboarding_next': '下一步',
      'onboarding_get_started': '开始使用',
      'onboarding_skip': '跳过',
      'story_done': '已完成',
      'story_chapter': '章节',
      'story_progress_chapter': '章节进度',
      'story_chapters_count': '5个章节 · 自动播放',
      'theme_light_sub': '清晰明亮模式',
      'theme_dark_sub': '默认深色模式',
      'theme_system_sub': '跟随系统设置',
      'btn_back': '返回',
      'story_syncing': '正在同步',
      'story_speaking': '正在解说…',
      'story_chapter_complete': '✓ 章节完成',
      'story_all_complete': '🎬 故事已完结 — 已播放全部5章',
      'story_paused_msg': '已暂停 — 点击播放以继续',
    },
  };
}
