import 'dart:async';
import 'package:climate_storyteller/core/storage/secure_storage_service.dart';
import 'package:climate_storyteller/features/narrator/narration_result.dart';

class AppLanguage {
  final String name;
  final String nativeName;
  final String code; // ISO-639-1 code
  final String localeCode;
  final Map<VoiceStyle, String> cloudTtsVoices;

  const AppLanguage({
    required this.name,
    required this.nativeName,
    required this.code,
    required this.localeCode,
    required this.cloudTtsVoices,
  });
}

class LanguageService {
  LanguageService._();
  static final LanguageService instance = LanguageService._();

  AppLanguage _currentLanguage = supportedLanguages.first; // Default to English
  final _streamCtrl = StreamController<AppLanguage>.broadcast();

  Stream<AppLanguage> get languageStream => _streamCtrl.stream;
  AppLanguage get currentLanguage => _currentLanguage;

  static const List<AppLanguage> supportedLanguages = [
    AppLanguage(
      name: 'English',
      nativeName: 'English',
      code: 'en',
      localeCode: 'en-US',
      cloudTtsVoices: {
        VoiceStyle.natural: 'en-US-Neural2-F',
        VoiceStyle.poetic: 'en-US-News-K',
        VoiceStyle.scientific: 'en-US-Neural2-H',
      },
    ),
    AppLanguage(
      name: 'Spanish',
      nativeName: 'Español',
      code: 'es',
      localeCode: 'es-ES',
      cloudTtsVoices: {
        VoiceStyle.natural: 'es-ES-Neural2-F',
        VoiceStyle.poetic: 'es-ES-Polyglot-1',
        VoiceStyle.scientific: 'es-ES-Neural2-F',
      },
    ),
    AppLanguage(
      name: 'French',
      nativeName: 'Français',
      code: 'fr',
      localeCode: 'fr-FR',
      cloudTtsVoices: {
        VoiceStyle.natural: 'fr-FR-Neural2-B',
        VoiceStyle.poetic: 'fr-FR-Polyglot-1',
        VoiceStyle.scientific: 'fr-FR-Neural2-C',
      },
    ),
    AppLanguage(
      name: 'German',
      nativeName: 'Deutsch',
      code: 'de',
      localeCode: 'de-DE',
      cloudTtsVoices: {
        VoiceStyle.natural: 'de-DE-Neural2-F',
        VoiceStyle.poetic: 'de-DE-Polyglot-1',
        VoiceStyle.scientific: 'de-DE-Neural2-H',
      },
    ),
    AppLanguage(
      name: 'Portuguese',
      nativeName: 'Português',
      code: 'pt',
      localeCode: 'pt-BR',
      cloudTtsVoices: {
        VoiceStyle.natural: 'pt-BR-Neural2-F',
        VoiceStyle.poetic: 'pt-BR-Polyglot-1',
        VoiceStyle.scientific: 'pt-BR-Neural2-H',
      },
    ),
    AppLanguage(
      name: 'Italian',
      nativeName: 'Italiano',
      code: 'it',
      localeCode: 'it-IT',
      cloudTtsVoices: {
        VoiceStyle.natural: 'it-IT-Neural2-C',
        VoiceStyle.poetic: 'it-IT-Polyglot-1',
        VoiceStyle.scientific: 'it-IT-Neural2-A',
      },
    ),
    AppLanguage(
      name: 'Hindi',
      nativeName: 'हिन्दी',
      code: 'hi',
      localeCode: 'hi-IN',
      cloudTtsVoices: {
        VoiceStyle.natural: 'hi-IN-Neural2-D',
        VoiceStyle.poetic: 'hi-IN-Neural2-F',
        VoiceStyle.scientific: 'hi-IN-Neural2-C',
      },
    ),
    AppLanguage(
      name: 'Japanese',
      nativeName: '日本語',
      code: 'ja',
      localeCode: 'ja-JP',
      cloudTtsVoices: {
        VoiceStyle.natural: 'ja-JP-Neural2-B',
        VoiceStyle.poetic: 'ja-JP-Neural2-C',
        VoiceStyle.scientific: 'ja-JP-Neural2-D',
      },
    ),
    AppLanguage(
      name: 'Chinese',
      nativeName: '中文',
      code: 'zh',
      localeCode: 'zh-CN',
      cloudTtsVoices: {
        VoiceStyle.natural: 'zh-CN-Neural2-F',
        VoiceStyle.poetic: 'zh-CN-Wavenet-B',
        VoiceStyle.scientific: 'zh-CN-Neural2-C',
      },
    ),
  ];

  Future<void> init() async {
    final code = await SecureStorageService.instance.getLanguageCode();
    if (code != null) {
      final match = supportedLanguages.firstWhere(
        (l) => l.code == code,
        orElse: () => supportedLanguages.first,
      );
      _currentLanguage = match;
    }
  }

  Future<void> setLanguage(String code) async {
    final match = supportedLanguages.firstWhere(
      (l) => l.code == code,
      orElse: () => supportedLanguages.first,
    );
    _currentLanguage = match;
    await SecureStorageService.instance.saveLanguageCode(code);
    _streamCtrl.add(match);
  }

  String translate(String key) {
    final langCode = _currentLanguage.code;
    return _translations[langCode]?[key] ?? _translations['en']?[key] ?? key;
  }

  static const Map<String, Map<String, String>> _translations = {
    'en': {
      'nav_explore': 'Explore',
      'nav_timeline': 'Timeline',
      'nav_narrator': 'Narrator',
      'nav_insights': 'Insights',
      'nav_story': 'Story',
      'nav_forest': 'Forest',
      'nav_settings': 'Settings',
      'settings_title': 'Settings',
      'sec_application': 'Application',
      'sec_api_keys': 'API Keys',
      'sec_about': 'About',
      'tile_language': 'Language',
      'tile_theme': 'Theme Mode',
      'theme_light': 'Light Mode',
      'theme_dark': 'Dark Mode',
      'theme_system': 'System Default',
      'tile_data_sources': 'Data Sources',
      'data_sources_title': 'Climate Data Sources',
      'data_sources_sub': 'How we retrieve & render Earth data',
      'ds_data_provided': 'Data Provided',
      'ds_how_we_get_it': 'How We Get It',
      'ds_nasa_gibs_desc': 'High-resolution satellite imagery tiles & environmental raster overlays.',
      'ds_nasa_gibs_how': 'Fetches real-time WMTS (EPSG:4326) tile layers directly from NASA Earthdata servers and formats them into dynamic KML GroundOverlays.',
      'ds_noaa_desc': 'Historical temperature anomalies, mean sea level trends, and NSIDC ice index.',
      'ds_noaa_how': 'Queries NOAA Climate Data Online API (v2) and Tides & Currents REST endpoints, generating Placemark time series on Liquid Galaxy.',
      'ds_ipcc_desc': 'CMIP6 climate projections and SSP scenarios (SSP1-2.6 to SSP5-8.5).',
      'ds_ipcc_how': 'Embeds IPCC 6th Assessment Report WGI/WGII dataset models with multi-era placemarks and regional boundary polygons.',
      'ds_openaq_desc': 'Global real-time PM2.5, PM10, NO2, and ground O3 air quality data.',
      'ds_openaq_how': 'Calls OpenAQ REST API v2 for live atmospheric readings across global megacities with intelligent offline estimations.',
      'ds_gfw_desc': 'Tropical deforestation alerts, canopy cover loss, and active fire tracking.',
      'ds_gfw_how': 'Parses NASA FIRMS VIIRS active fire CSV feeds and Hansen/UMD forest change data rendered directly onto Liquid Galaxy screens.',
      'tile_kml_cache': 'KML Cache',
      'tile_kml_cache_sub': 'Download offline KML files for demo day',
      'tile_lg_diagnostics': 'LG Diagnostics',
      'tile_lg_diagnostics_sub': 'Run connection and configuration tests',
      'tile_api_setup': 'API Setup',
      'tile_api_setup_sub': 'Gemini API key, Flutter TTS',
      'tile_about_sub': 'GSoC 2026 · Liquid Galaxy Project · v1.0.0',
      'btn_disconnect': 'Disconnect',
      'btn_connect_lg': 'Connect to LG Rig',
      'narrator_title': 'AI Narrator',
      'narrator_subtitle': 'Gemini · Google TTS',
      'badge_now_playing': 'NOW PLAYING',
      'badge_ready': 'READY',
      'txt_no_gemini_key': 'No Gemini key set. Go to Settings → API Setup.',
      'sec_region': 'Region',
      'sec_era': 'Era',
      'sec_voice_style': 'Voice Style',
      'sec_generated_narration': 'Generated Narration',
      'btn_generate_play': 'Generate & Play Narration',
      'btn_generating': 'Generating narration…',
      'btn_close': 'Close',
      'about_description': 'Climate Change Storyteller is a multi-screen visualization platform for Liquid Galaxy. It displays interactive KML layers and timelines to tell the story of Earth\'s changing climate.',
      'about_org': 'Organization',
      'about_prog': 'Program',
      'about_sys': 'Target System',
      'about_tech': 'Core Tech',
    },
    'es': {
      'nav_explore': 'Explorar',
      'nav_timeline': 'Cronología',
      'nav_narrator': 'Narrador',
      'nav_insights': 'Estadísticas',
      'nav_story': 'Historia',
      'nav_forest': 'Bosque',
      'nav_settings': 'Ajustes',
      'settings_title': 'Ajustes',
      'sec_application': 'Aplicación',
      'sec_api_keys': 'Claves de API',
      'sec_about': 'Acerca de',
      'tile_language': 'Idioma',
      'tile_data_sources': 'Fuentes de datos',
      'tile_kml_cache': 'Caché de KML',
      'tile_kml_cache_sub': 'Descargar archivos KML sin conexión para el día de demostración',
      'tile_lg_diagnostics': 'Diagnósticos de LG',
      'tile_lg_diagnostics_sub': 'Ejecutar pruebas de conexión y configuración',
      'tile_api_setup': 'Configuración de API',
      'tile_api_setup_sub': 'Clave de Gemini, TTS de Flutter',
      'tile_about_sub': 'GSoC 2026 · Liquid Galaxy Project · v1.0.0',
      'btn_disconnect': 'Desconectar',
      'btn_connect_lg': 'Conectarse a LG Rig',
      'narrator_title': 'Narrador de IA',
      'narrator_subtitle': 'Gemini · Google TTS',
      'badge_now_playing': 'REPRODUCIENDO',
      'badge_ready': 'LISTO',
      'txt_no_gemini_key': 'Clave de Gemini no configurada. Vaya a Ajustes → Configuración de API.',
      'sec_region': 'Región',
      'sec_era': 'Época',
      'sec_voice_style': 'Estilo de voz',
      'sec_generated_narration': 'Narración generada',
      'btn_generate_play': 'Generar y reproducir narración',
      'btn_generating': 'Generando narración…',
      'btn_close': 'Cerrar',
      'about_description': 'Climate Change Storyteller es una plataforma de visualización multipantalla para Liquid Galaxy. Muestra capas KML interactivas y líneas de tiempo para contar la historia del cambio climático de la Tierra.',
      'about_org': 'Organización',
      'about_prog': 'Programa',
      'about_sys': 'Sistema objetivo',
      'about_tech': 'Tecnología central',
    },
    'fr': {
      'nav_explore': 'Explorer',
      'nav_timeline': 'Chronologie',
      'nav_narrator': 'Narrateur',
      'nav_insights': 'Statistiques',
      'nav_story': 'Histoire',
      'nav_forest': 'Forêt',
      'nav_settings': 'Paramètres',
      'settings_title': 'Paramètres',
      'sec_application': 'Application',
      'sec_api_keys': 'Clés API',
      'sec_about': 'À propos',
      'tile_language': 'Langue',
      'tile_data_sources': 'Sources de données',
      'tile_kml_cache': 'Cache KML',
      'tile_kml_cache_sub': 'Télécharger les fichiers KML hors ligne pour la démo',
      'tile_lg_diagnostics': 'Diagnostics LG',
      'tile_lg_diagnostics_sub': 'Lancer les tests de connexion et de configuration',
      'tile_api_setup': 'Configuration de l\'API',
      'tile_api_setup_sub': 'Clé API Gemini, Flutter TTS',
      'tile_about_sub': 'GSoC 2026 · Projet Liquid Galaxy · v1.0.0',
      'btn_disconnect': 'Déconnecter',
      'btn_connect_lg': 'Connexion au rig LG',
      'narrator_title': 'Narrateur IA',
      'narrator_subtitle': 'Gemini · Google TTS',
      'badge_now_playing': 'EN LECTURE',
      'badge_ready': 'PRÊT',
      'txt_no_gemini_key': 'Clé Gemini non configurée. Allez dans Paramètres → Configuration de l\'API.',
      'sec_region': 'Région',
      'sec_era': 'Ère',
      'sec_voice_style': 'Style de voix',
      'sec_generated_narration': 'Narration générée',
      'btn_generate_play': 'Générer et lire la narration',
      'btn_generating': 'Génération de la narration…',
      'btn_close': 'Fermer',
      'about_description': 'Climate Change Storyteller est une plateforme de visualisation multi-écrans pour Liquid Galaxy. Elle affiche des couches KML interactives et des chronologies pour raconter l\'histoire du changement climatique de la Terre.',
      'about_org': 'Organisation',
      'about_prog': 'Programme',
      'about_sys': 'Système cible',
      'about_tech': 'Technologie de base',
    },
    'de': {
      'nav_explore': 'Erkunden',
      'nav_timeline': 'Zeitstrahl',
      'nav_narrator': 'Erzähler',
      'nav_insights': 'Einblicke',
      'nav_story': 'Geschichte',
      'nav_forest': 'Wald',
      'nav_settings': 'Einstellungen',
      'settings_title': 'Einstellungen',
      'sec_application': 'Anwendung',
      'sec_api_keys': 'API-Schlüssel',
      'sec_about': 'Über',
      'tile_language': 'Sprache',
      'tile_data_sources': 'Datenquellen',
      'tile_kml_cache': 'KML-Cache',
      'tile_kml_cache_sub': 'KML-Dateien für den Offline-Modus herunterladen',
      'tile_lg_diagnostics': 'LG-Diagnose',
      'tile_lg_diagnostics_sub': 'Verbindungs- und Konfigurationstests ausführen',
      'tile_api_setup': 'API-Einrichtung',
      'tile_api_setup_sub': 'Gemini-API-Schlüssel, Flutter TTS',
      'tile_about_sub': 'GSoC 2026 · Liquid Galaxy Project · v1.0.0',
      'btn_disconnect': 'Trennen',
      'btn_connect_lg': 'Mit LG-Rig verbinden',
      'narrator_title': 'KI-Erzähler',
      'narrator_subtitle': 'Gemini · Google TTS',
      'badge_now_playing': 'WIRD ABGESPIELT',
      'badge_ready': 'BEREIT',
      'txt_no_gemini_key': 'Kein Gemini-Schlüssel festgelegt. Gehen Sie zu Einstellungen → API-Einrichtung.',
      'sec_region': 'Region',
      'sec_era': 'Ära',
      'sec_voice_style': 'Stimme-Stil',
      'sec_generated_narration': 'Generierte Erzählung',
      'btn_generate_play': 'Erzählung generieren & abspielen',
      'btn_generating': 'Erzählung wird generiert…',
      'btn_close': 'Schließen',
      'about_description': 'Climate Change Storyteller ist eine Multi-Screen-Visualisierungsplattform für Liquid Galaxy. Sie zeigt interaktive KML-Ebenen und Zeitleisten an, um die Geschichte des Klimawandels der Erde zu erzählen.',
      'about_org': 'Organisation',
      'about_prog': 'Programm',
      'about_sys': 'Zielsystem',
      'about_tech': 'Kerntechnologie',
    },
    'pt': {
      'nav_explore': 'Explorar',
      'nav_timeline': 'Cronologia',
      'nav_narrator': 'Narrador',
      'nav_insights': 'Estatísticas',
      'nav_story': 'História',
      'nav_forest': 'Floresta',
      'nav_settings': 'Ajustes',
      'settings_title': 'Ajustes',
      'sec_application': 'Aplicação',
      'sec_api_keys': 'Chaves de API',
      'sec_about': 'Sobre',
      'tile_language': 'Idioma',
      'tile_data_sources': 'Fontes de Dados',
      'tile_kml_cache': 'Cache de KML',
      'tile_kml_cache_sub': 'Baixar arquivos KML off-line para demonstração',
      'tile_lg_diagnostics': 'Diagnósticos do LG',
      'tile_lg_diagnostics_sub': 'Executar testes de conexão e configuração',
      'tile_api_setup': 'Configuração de API',
      'tile_api_setup_sub': 'Chave de API Gemini, Flutter TTS',
      'tile_about_sub': 'GSoC 2026 · Liquid Galaxy Project · v1.0.0',
      'btn_disconnect': 'Desconectar',
      'btn_connect_lg': 'Conectar ao LG Rig',
      'narrator_title': 'Narrador de IA',
      'narrator_subtitle': 'Gemini · Google TTS',
      'badge_now_playing': 'REPRODUZINDO',
      'badge_ready': 'PRONTO',
      'txt_no_gemini_key': 'Nenhuma chave Gemini definida. Vá em Ajustes → Configuração de API.',
      'sec_region': 'Região',
      'sec_era': 'Era',
      'sec_voice_style': 'Estilo de voz',
      'sec_generated_narration': 'Narrativa Gerada',
      'btn_generate_play': 'Gerar e Reproduzir Narrativa',
      'btn_generating': 'Gerando narrativa…',
      'btn_close': 'Fechar',
      'about_description': 'Climate Change Storyteller é uma plataforma de visualização multi-telas para o Liquid Galaxy. Ela exibe camadas KML interativas e cronogramas para contar a história da mudança climática da Terra.',
      'about_org': 'Organização',
      'about_prog': 'Programa',
      'about_sys': 'Sistema de destino',
      'about_tech': 'Tecnologia central',
    },
    'it': {
      'nav_explore': 'Esplora',
      'nav_timeline': 'Cronologia',
      'nav_narrator': 'Narratore',
      'nav_insights': 'Analisi',
      'nav_story': 'Storia',
      'nav_forest': 'Foresta',
      'nav_settings': 'Impostazioni',
      'settings_title': 'Impostazioni',
      'sec_application': 'Applicazione',
      'sec_api_keys': 'Chiavi API',
      'sec_about': 'Informazioni',
      'tile_language': 'Lingua',
      'tile_data_sources': 'Fonti dati',
      'tile_kml_cache': 'Cache KML',
      'tile_kml_cache_sub': 'Scarica file KML offline per il giorno della demo',
      'tile_lg_diagnostics': 'Diagnostica LG',
      'tile_lg_diagnostics_sub': 'Esegui test di connessione e configurazione',
      'tile_api_setup': 'Configurazione API',
      'tile_api_setup_sub': 'Chiave API Gemini, Flutter TTS',
      'tile_about_sub': 'GSoC 2026 · Liquid Galaxy Project · v1.0.0',
      'btn_disconnect': 'Disconnetti',
      'btn_connect_lg': 'Connetti a LG Rig',
      'narrator_title': 'Narratore IA',
      'narrator_subtitle': 'Gemini · Google TTS',
      'badge_now_playing': 'IN RIPRODUZIONE',
      'badge_ready': 'PRONTO',
      'txt_no_gemini_key': 'Nessuna chiave Gemini configurata. Vai in Impostazioni → Configurazione API.',
      'sec_region': 'Regione',
      'sec_era': 'Era',
      'sec_voice_style': 'Stile voce',
      'sec_generated_narration': 'Narrazione Generata',
      'btn_generate_play': 'Genera e riproduci narrazione',
      'btn_generating': 'Generazione narrazione…',
      'btn_close': 'Chiudi',
      'about_description': 'Climate Change Storyteller è una piattaforma di visualizzazione multi-schermo per Liquid Galaxy. Mostra livelli KML interattivi e linee temporali per raccontare la storia del cambiamento climatico terrestre.',
      'about_org': 'Organizzazione',
      'about_prog': 'Programma',
      'about_sys': 'Sistema target',
      'about_tech': 'Tecnologia di base',
    },
    'hi': {
      'nav_explore': 'अन्वेषण',
      'nav_timeline': 'समयरेखा',
      'nav_narrator': 'कथावाचक',
      'nav_insights': 'आंकड़े',
      'nav_story': 'कहानी',
      'nav_forest': 'वन',
      'nav_settings': 'सेटिंग्स',
      'settings_title': 'सेटिंग्स',
      'sec_application': 'एप्लिकेशन',
      'sec_api_keys': 'एपीआई कुंजी',
      'sec_about': 'के बारे में',
      'tile_language': 'भाषा',
      'tile_data_sources': 'डेटा स्रोत',
      'tile_kml_cache': 'केएमएल कैश',
      'tile_kml_cache_sub': 'डेमो डे के लिए ऑफ़लाइन केएमएल फ़ाइलें डाउनलोड करें',
      'tile_lg_diagnostics': 'एलजी निदान',
      'tile_lg_diagnostics_sub': 'कनेक्शन और कॉन्फ़िगरेशन परीक्षण चलाएं',
      'tile_api_setup': 'एपीआई सेटअप',
      'tile_api_setup_sub': 'जेमिनी एपीआई कुंजी, फ़्लटर टीटीएस',
      'tile_about_sub': 'GSoC 2026 · लिक्विड गैलेक्सी प्रोजेक्ट · v1.0.0',
      'btn_disconnect': 'डिस्कनेक्ट करें',
      'btn_connect_lg': 'एलजी रिग से कनेक्ट करें',
      'narrator_title': 'एआई कथावाचक',
      'narrator_subtitle': 'जेमिनी · गूगल टीटीएस',
      'badge_now_playing': 'अब बज रहा है',
      'badge_ready': 'तैयार',
      'txt_no_gemini_key': 'कोई जेमिनी कुंजी सेट नहीं है। सेटिंग्स → एपीआई सेटअप पर जाएं।',
      'sec_region': 'क्षेत्र',
      'sec_era': 'युग',
      'sec_voice_style': 'आवाज शैली',
      'sec_generated_narration': 'उत्पन्न विवरण',
      'btn_generate_play': 'कथा उत्पन्न करें और चलाएं',
      'btn_generating': 'कथा उत्पन्न हो रही है…',
      'btn_close': 'बंद करें',
      'about_description': 'क्लाइमेट चेंज स्टोरीटेलर लिक्विड गैलेक्सी के लिए एक मल्टी-स्क्रीन विज़ुअलाइज़ेशन प्लेटफ़ॉर्म है। यह पृथ्वी के बदलते जलवायु की कहानी बताने के लिए इंटरैक्टिव केएमएल लेयर्स और टाइमलाइन प्रदर्शित करता है।',
      'about_org': 'संगठन',
      'about_prog': 'कार्यक्रम',
      'about_sys': 'लक्षित प्रणाली',
      'about_tech': 'मुख्य तकनीक',
    },
    'ja': {
      'nav_explore': '探索',
      'nav_timeline': 'タイムライン',
      'nav_narrator': 'ナレーター',
      'nav_insights': 'データ分析',
      'nav_story': 'ストーリー',
      'nav_forest': '森林',
      'nav_settings': '設定',
      'settings_title': '設定',
      'sec_application': 'アプリケーション',
      'sec_api_keys': 'APIキー',
      'sec_about': '情報',
      'tile_language': '言語',
      'tile_data_sources': 'データソース',
      'tile_kml_cache': 'KMLキャッシュ',
      'tile_kml_cache_sub': 'デモ用のオフラインKMLファイルをダウンロード',
      'tile_lg_diagnostics': 'LG診断',
      'tile_lg_diagnostics_sub': '接続および構成のテストを実行します',
      'tile_api_setup': 'API設定',
      'tile_api_setup_sub': 'Gemini APIキー、Flutter TTS',
      'tile_about_sub': 'GSoC 2026 · Liquid Galaxy Project · v1.0.0',
      'btn_disconnect': '切断',
      'btn_connect_lg': 'LGリグに接続',
      'narrator_title': 'AIナレーター',
      'narrator_subtitle': 'Gemini · Google TTS',
      'badge_now_playing': '再生中',
      'badge_ready': '準備完了',
      'txt_no_gemini_key': 'Geminiキーが設定されていません。設定 → API設定に進んでください。',
      'sec_region': '地域',
      'sec_era': '年代',
      'sec_voice_style': '音声スタイル',
      'sec_generated_narration': '生成されたナレーション',
      'btn_generate_play': 'ナレーションを生成して再生',
      'btn_generating': 'ナレーションを生成中…',
      'btn_close': '閉じる',
      'about_description': 'Climate Change Storytellerは、Liquid Galaxy向けのマルチスクリーン視覚化プラットフォームです。インタラクティブなKMLレイヤーとタイムラインを表示して、地球の気候変動のストーリーを伝えます。',
      'about_org': '組織',
      'about_prog': 'プログラム',
      'about_sys': '対象システム',
      'about_tech': '主要技術',
    },
    'zh': {
      'nav_explore': '探索',
      'nav_timeline': '时间线',
      'nav_narrator': '解说',
      'nav_insights': '数据分析',
      'nav_story': '故事',
      'nav_forest': '森林',
      'nav_settings': '设置',
      'settings_title': '设置',
      'sec_application': '应用设置',
      'sec_api_keys': 'API密钥',
      'sec_about': '关于',
      'tile_language': '语言',
      'tile_data_sources': '数据源',
      'tile_kml_cache': 'KML缓存',
      'tile_kml_cache_sub': '下载用于演示日的离线KML文件',
      'tile_lg_diagnostics': 'LG诊断',
      'tile_lg_diagnostics_sub': '运行连接与配置诊断测试',
      'tile_api_setup': 'API配置',
      'tile_api_setup_sub': 'Gemini API密钥, Flutter TTS',
      'tile_about_sub': 'GSoC 2026 · 液态银河项目 · v1.0.0',
      'btn_disconnect': '断开连接',
      'btn_connect_lg': '连接至液态银河',
      'narrator_title': 'AI解说员',
      'narrator_subtitle': 'Gemini · Google语音合成',
      'badge_now_playing': '正在播放',
      'badge_ready': '就绪',
      'txt_no_gemini_key': '未配置Gemini密钥。请前往设置 → API配置。',
      'sec_region': '地区',
      'sec_era': '纪元',
      'sec_voice_style': '声音风格',
      'sec_generated_narration': '生成的解说词',
      'btn_generate_play': '生成并播放解说词',
      'btn_generating': '正在生成解说词…',
      'btn_close': '关闭',
      'about_description': 'Climate Change Storyteller 是适用于液态银河（Liquid Galaxy）的多屏可视化平台。它通过交互式 KML 图层和时间线，向人们讲述地球气候变化的故事。',
      'about_org': '组织',
      'about_prog': '项目',
      'about_sys': '目标系统',
      'about_tech': '核心技术',
    },
  };
}
